apply plugin: 'com.android.library'

android {
    compileSdkVersion 28
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
    }

    defaultConfig {
        minSdkVersion 21
        //noinspection ExpiredTargetSdkVersion
        targetSdkVersion 22
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        abortOnError false
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    api project(":mesdk")
}

//*****************************************************//
def version = "3.10.90"
def mesdkName = "MESDK-"+version+"-RELEASE.jar"
def mesdkaarName = "MESDK-"+version+"-RELEASE.aar"
def mesdkThirdAARName = "MESDK-SIMPLE-"+version+"-RELEASE.aar"


task copyassets(type:Copy){
    delete("assets")
//    from("../SDKDemo/src/main/assets")
    from("../SDKDemo/src/main/assets/BmpFonts.DZK")
    from("../ThirdParty/libNDK_EMV.so")
    from("../ThirdParty/libemv_sp.so")
    into("assets")
}

task copycompatibleEMVLibs(type:Copy){
    delete("libs")
    from("../ThirdParty/compatibleEMVLibs")
    from("../mesdk/target/"+mesdkName)
    into("libs")
}



task copyL2EMVLibsLibs(type:Copy){
    delete("libs")
    from("../ThirdParty/L2EMVLibs")
    from("../mesdk/target/"+mesdkName)
    into("libs")
}

task copyL3EMVLibsLibs(type:Copy){
    delete("libs")
    from("../ThirdParty/L3EMVLibs")
    from("../mesdk/target/"+mesdkName)
    into("libs")
}

task DeviceModuleLibs(type:Copy){
    delete("libs")
    from("../ThirdParty/compatibleEMVLibs")
    from("../mesdk/target/"+mesdkName)
    into("libs")
}

//+++++++++++++++++++++++++++++++++++//
task L2EMVLibspre(dependsOn:["copyassets","copyL2EMVLibsLibs"]){
    println(">>>start L2EMVLibspre")
}

task L3EMVLibspre(dependsOn:["copyassets","copyL3EMVLibsLibs"]){
    println(">>>start L3EMVLibspre")
}

task L23EMVpre(dependsOn:["copyassets","copycompatibleEMVLibs"]){
    println(">>>start compatibleEMVpre")
}

task DeviceModulepre(dependsOn:["copyassets","DeviceModuleLibs"]){
    println(">>>start DeviceModulepre")
    doLast {
        delete("libs/armeabi-v7a/libemvl2jni.so");
        delete("libs/armeabi-v7a/libemvl3jni.so");
        delete("libs/arm64-v8a/libemvl3jni.so");
        delete("libs/arm64-v8a/libemvl2jni.so");
    }
}

//+++++++++++++++++++++++++++++++++++//
task aarL2EMVLibs(type:Copy,dependsOn:["L2EMVLibspre","build"]){
    println(">>>start aarL2EMVLibs")
    delete("../OUTPUT/meEMV/aar/")
    from("./build/outputs/aar/buildTask-release.aar")
    into("../OUTPUT/meEMV/aar/")
    rename("buildTask-release.aar",mesdkaarName)
}

task aarL3EMVLibs(type:Copy,dependsOn:["L3EMVLibspre","build"]){
    println(">>>start aarL3EMVLibs")
    delete("../OUTPUT/l3EMV/aar/")
    from("./build/outputs/aar/buildTask-release.aar")
    into("../OUTPUT/l3EMV/aar/")
    rename("buildTask-release.aar",mesdkaarName)
}

task aarcompatibleEMV(type:Copy,dependsOn:["L23EMVpre","build"]){
    println(">>>start aarcompatibleEMV")
    delete("../OUTPUT/compatibleEMV/aar/")
    from("./build/outputs/aar/buildTask-release.aar")
    into("../OUTPUT/compatibleEMV/aar/")
    rename("buildTask-release.aar",mesdkaarName)
}

task aarDeviceModule(type:Copy,dependsOn:["DeviceModulepre","build"]){
    println(">>>start aarDeviceModule")
    delete("../OUTPUT/DeviceModule/aar/")
    from("./build/outputs/aar/buildTask-release.aar")
    into("../OUTPUT/DeviceModule/aar/")
    rename("buildTask-release.aar",mesdkaarName)
}

task copySimpleSDKLibs(type:Copy){
    delete("libs")
    from("../ThirdParty/SimpleSDKLibs")
    from("../mesdk/target/"+mesdkName)
    into("libs")
}

task simpleSDKPre(type:Copy,dependsOn:["copySimpleSDKLibs"]){
    println(">>>start copySimpleSDKLibs")
}

//打包只有扫码和打印功能的包
task aarSimpleSDK(type:Copy,dependsOn:["simpleSDKPre","build"]){
    println(">>>start aarSimpleSDKLibs")
    delete("../OUTPUT/SimpleSDK/aar/")
    from("./build/outputs/aar/buildTask-release.aar")
    into("../OUTPUT/SimpleSDK/aar/")
    rename("buildTask-release.aar",mesdkThirdAARName)
}

//================================================================================================//
def mesdkVer = file("./src/sdk.properties").getText().split("=")[1]
def outJarPath = "../OUTPUT/compatibleEMV/libs/"
def mesdkJarName = "MESDK-"+mesdkVer+"-INIT.jar"//未混淆的Jar
def proguardMesdkJarName = "MESDK-"+mesdkVer+"-RELEASE.jar"//混淆的Jar
//def classesJarPath = "/intermediates/intermediate-jars/release/classes.jar"
def classesJarPath = "/intermediates/compile_library_classes_jar/release/classes.jar"
//def classesJarPath = "/intermediates/compile_library_classes/release/classes.jar"
//def classesJarPath = "/intermediates/compile_library_classes/release/classes.jar"
def thirdJarPath = "../ThirdParty/"

task AmakeMesdkJar(type:Jar) {
    delete(outJarPath)
    archiveName = mesdkJarName
    from(project.zipTree(project(":nmjs-api").buildDir.absolutePath+classesJarPath))
    from(project.zipTree(project(":devicemodule").buildDir.absolutePath+classesJarPath))
    from(project.zipTree(project(":scanmodule").buildDir.absolutePath+classesJarPath))
    from(project.zipTree(project(":meEMVModule").buildDir.absolutePath+classesJarPath))
    from(project.zipTree(project(":mesdk").buildDir.absolutePath+classesJarPath))
    from(project.zipTree(thirdJarPath+"EMVJNIService.jar"))
    from(project.zipTree(thirdJarPath+"intelligentLibrary.jar"))
    from(project.zipTree(thirdJarPath+"k21.jar"))
    from(project.zipTree(thirdJarPath+"k21Transation.jar"))
    from(project.zipTree(thirdJarPath+"ndk.jar"))
    from(project.zipTree(thirdJarPath+"newland.jar"))
    from(project.zipTree(thirdJarPath+"stream-1.2.1.jar"))
    from(project.zipTree(thirdJarPath+"UartPort.jar"))
    from(project.zipTree(thirdJarPath+"BluetoothControl_1.0.27.3.jar"))
    destinationDir = file(outJarPath)
    exclude('**/R.class')
    exclude('**/R\$*.class')
}

task AproguardMesdkJar(type:proguard.gradle.ProGuardTask,dependsOn:["AmakeMesdkJar"]){
    injars outJarPath+mesdkJarName
    outjars outJarPath+proguardMesdkJarName
    configuration 'mesdkjar-proguard-rules.pro'
}

task AcopyLibs(type:Copy,dependsOn:["AproguardMesdkJar"]){
    delete("libs")
    from("../ThirdParty/compatibleEMVLibs")
    from(outJarPath+proguardMesdkJarName)
    into("libs")
}

task AcopyAssets(type:Copy){
    delete("assets")
    from("../SDKDemo/src/main/assets/BmpFonts.DZK")
    from("../ThirdParty/libNDK_EMV.so")
    from("../ThirdParty/libemv_sp.so")
    into("assets")
}

task AoutMesdkAAR(type:Copy,dependsOn:["AcopyLibs","AcopyAssets","build"]){
    delete("../OUTPUT/compatibleEMV/aar/")
    from("./build/outputs/aar/buildTask-release.aar")
    into("../OUTPUT/compatibleEMV/aar/")
    rename("buildTask-release.aar",proguardMesdkJarName.substring(0,proguardMesdkJarName.length()-3)+"aar")
}



