buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            allowInsecureProtocol = true
            url'http://192.168.33.231:8081/repository/maven-releases/'
        }
        maven {
            url "https://jitpack.io"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        // AGP8 兼容的 fat-aar fork（将依赖打包进 aar），坐标来自 JitPack
        classpath 'com.github.shenghua-ok:fat-aar-android:1.4.6'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}