buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            allowInsecureProtocol = true
            url'http://192.168.33.231:8081/repository/maven-releases/'
        }
        maven {
            url "https://jitpack.io"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
    }
}

ext {
    autotestVersionCode = 20005
    autotestVersionName = '2.0.04'
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

tasks.register('publishAutoTest') {
    group = 'publishing'
    description = '构建并发布 auto-test AAR 到项目内 local-maven-repo'
    dependsOn ':auto-test:publishReleasePublicationToLocalMavenRepoRepository'
}