package com.newland.nsdk.core.api.internal.crypto;

import com.newland.nsdk.core.api.common.Module;
import com.newland.nsdk.core.api.common.crypto.AsymAlgorithmParameters;
import com.newland.nsdk.core.api.common.crypto.AsymEncodingMode;
import com.newland.nsdk.core.api.common.crypto.CSRFileType;
import com.newland.nsdk.core.api.common.crypto.CSRParameters;
import com.newland.nsdk.core.api.common.crypto.CipherOutput;
import com.newland.nsdk.core.api.common.crypto.CipherParameters;
import com.newland.nsdk.core.api.common.crypto.CipherType;
import com.newland.nsdk.core.api.common.crypto.CryptogramInfo;
import com.newland.nsdk.core.api.common.crypto.GCMCipherOut;
import com.newland.nsdk.core.api.common.crypto.MACOutput;
import com.newland.nsdk.core.api.common.crypto.MACType;
import com.newland.nsdk.core.api.common.crypto.PaddingMode;
import com.newland.nsdk.core.api.common.exception.NSDKException;
import com.newland.nsdk.core.api.common.keymanager.AsymmetricKey;
import com.newland.nsdk.core.api.common.keymanager.DUKPTDerivateKey;
import com.newland.nsdk.core.api.common.keymanager.DUKPTDerivateUsage;
import com.newland.nsdk.core.api.common.keymanager.Key;
import com.newland.nsdk.core.api.common.keymanager.KeyType;
import com.newland.nsdk.core.api.common.keymanager.KeyUsage;
import com.newland.nsdk.core.api.common.keymanager.SymmetricKey;
import com.newland.nsdk.core.api.internal.keymanager.KeyManager;

/**
 * Provides the ability to encrypt and decrypt data with keys in the PIN pad.
 *
 * <p>How to get this module:</p>
 * <pre>
 *     Crypto crypto = (Crypto)NSDKModuleManagerImpl.getInstance().getModule(ModuleType.CRYPTO);
 * </pre>
 */
public interface Crypto extends Module {
    /**
     * Generates MAC for a block of data with the specified key.
     *
     * <p>Example:</p>
     * <pre>
     *     byte keyId = 2;
     *     MACType macType = MACType.TDES_X99;
     *     byte[] data = ISOUtils.hex2byte("88888881113366677883373215563223abcdeffdaabbccdd");
     *
     *     try {
     *         MACOutput macOutput =  crypto.generateMAC(keyId, macType, null, data);
     *         if(macOutput!=null){
     *             // Handle the MAC result: macOutput.getData()
     *         }
     *     } catch(NSDKException e) {
     *         // Handle the exception
     *     }
     * </pre>
     *
     * @param keyId   <b>[Required]</b> The key used to generate MAC. This key shall already be generated by {@link KeyManager} before.
     * @param macType <b>[Required]</b> MAC type, see {@link MACType}
     * @param iv      <b>[Optional]</b> Initial Vector. This is required for CBC mode. 8 bytes for TDES, 16 bytes for AES.
     * @param data    <b>[Required]</b> The data used to generate MAC.
     * @return MAC output. See {@link MACOutput}.
     * @throws NSDKException
     */
    MACOutput generateMAC(byte keyId, MACType macType, byte[] iv, byte[] data) throws NSDKException;

    /**
     * Generates MAC for a block of data with derived key by AES DUKPT key.
     *
     * <p>Example:</p>
     * <pre>
     *     DUKPTDerivateKey key = new DUKPTDerivateKey();
     *     key.setKeyID((byte) 2);
     *     key.setDerivateKeyLen(16);
     *     key.setDerivateKeyType(KeyType.AES);
     *     key.setDerivateUsage(DUKPTDerivateUsage.MAC);
     *
     *     byte[] data = ISOUtils.hex2byte("88888881113366677883373215563223abcdeffdaabbccdd");
     *     try {
     *         MACOutput macOutput = crypto.generateMAC(key, MACType.AES_DUKPT_LAST, null, data);
     *         // Handle the MAC result: macOutput.getData()
     *     } catch (NSDKException e) {
     *         // Handle the exception
     *     }
     * </pre>
     *
     * @param key     Derived key by AES DUKPT key. The following parameters required:
     *                <ul>
     *                <li>{@link DUKPTDerivateKey#keyID}: AES DUKPT key ID</li>
     *                <li>{@link DUKPTDerivateKey#derivateKeyType}: Derived key type, see {@link KeyType}</li>
     *                <li>{@link DUKPTDerivateKey#derivateUsage}: Derived key usage, {@link DUKPTDerivateUsage#MAC_GEN}, {@link DUKPTDerivateUsage#MAC_VERIFY}, {@link DUKPTDerivateUsage#MAC_BOTH}</li>
     *                <li>{@link DUKPTDerivateKey#derivateKeyLen}: Derived key len. It shall be less than AES DUKPT key len. 16/24 for derived DES key. 16/24/32 for derived AES key.</li>
     *                </ul>
     * @param macType <b>[Required]</b> MAC type, see {@link MACType}. For {@link MACType#AES_DUKPT_X919} and {@link MACType#AES_DUKPT_UNIONPAY_ECB}, only DES key is allowed to derive.
     * @param iv      <b>[Optional]</b> Initial Vector. This is required for CBC mode. 8 bytes for TDES, 16 bytes for AES.
     * @param data    <b>[Required]</b> The data used to generate MAC.
     * @return MAC output. See {@link MACOutput}.
     * @throws NSDKException
     */
    MACOutput generateMAC(DUKPTDerivateKey key, MACType macType, byte[] iv, byte[] data) throws NSDKException;

    /**
     * Encrypts data with the key which is already exist in the PIN pad.
     *
     * <p>Example 1:</p>
     * <pre>
     *     SymmetricKey key = new SymmetricKey();
     *     key.setKeyID((byte) 2);
     *     key.setKeyUsage(KeyUsage.DATA);
     *
     *     byte[] data = ISOUtils.hex2byte("88888881113366677883373215563223abcdeffdaabbccdd");
     *
     *     try {
     *         CipherOutput cipherOutput =  crypto.encrypt(key, CipherType.DES_ECB, PaddingMode.NONE, null, data);
     *         // Handle the encrypted data: cipherOutput.getData()
     *     } catch(NSDKException e) {
     *         // Handle the exception
     *     }
     *
     * </pre>
     *
     * <p>Example 2: Using derived DUKPT key</p>
     * <pre>
     *     DUKPTDerivateKey desKey = new DUKPTDerivateKey();
     *     desKey.setKeyID((byte) 2);
     *     desKey.setKeyUsage(KeyUsage.DUKPT);
     *     desKey.setDerivateUsage(DUKPTDerivateUsage.DATA_ENC);
     *     desKey.setDerivateKeyType(KeyType.AES);
     *     desKey.setDerivateKeyLen(16);
     *
     *     byte[] data = ISOUtils.hex2byte("88888881113366677883373215563223abcdeffdaabbccdd8888888111336667");
     *     try {
     *         CipherOutput cipherOutput = crypto.encrypt(desKey, CipherType.AES_DUKPT_ECB, PaddingMode.NONE, null, data);
     *         // Handle the encrypted data: cipherOutput.getData()
     *     } catch (NSDKException e) {
     *         // Handle the exception
     *     }
     * </pre>
     *
     * @param key         <b>[Required]</b> The key used to encrypt data. see {@link SymmetricKey}. This key shall already be generated by {@link KeyManager#generateKey} before.
     *                    <ul>
     *                    <li>Key ID is required.</li>
     *                    <li>Default key usage: {@link KeyUsage#DATA}. If using derived DUKPT key, default key usage is {@link KeyUsage#DUKPT}</li>
     *                    <li>If using derived DUKPT key, the following required:
     *                    <ul>
     *                    <li>Derivate key type: see {@link KeyType}</li>
     *                    <li>Derivate key usage: {@link DUKPTDerivateUsage#DATA_ENC}, {@link DUKPTDerivateUsage#DATA_DEC}, {@link DUKPTDerivateUsage#DATA_BOTH}</li>
     *                    <li>Derivate key len: 16/24 for derived DES key, 16/24/32 for derived AES key. It shall be less than the len of AES DUKPT key.</li>
     *                    </ul>
     *                    </li>
     *                    </ul>
     * @param cipherType  <b>[Required]</b> Cipher type. See {@link CipherType}
     * @param paddingMode <b>[Optional]</b> Padding mode, see {@link PaddingMode}, default value is {@link PaddingMode#NONE} if this is set to null.
     * @param iv          <b>[Optional]</b> Initial vector required for CBC encryption. 8 bytes for TDES, 16 bytes for AES.
     * @param data        <b>[Required]</b> The data to be encrypted. Data length shall be multiple of 16 for AES. Data maximum length shall not be more than 2000.
     * @return Encryption result. See {@link CipherOutput}
     * @throws NSDKException
     */
    CipherOutput encrypt(SymmetricKey key, CipherType cipherType, PaddingMode paddingMode, byte[] iv, byte[] data) throws NSDKException;
    /**
     * Encrypts data with the key which is already exist in the PIN pad.
     *
     * <p>Example 1:</p>
     * <pre>
     *     SymmetricKey cryptoKey = new SymmetricKey();
     *     cryptoKey.setKeyID((byte) 3);
     *     cryptoKey.setKeyType(KeyType.AES);
     *     cryptoKey.setKeyUsage(KeyUsage.DATA);
     *     cryptoKey.setKeyLen(16);
     *     CipherParameters encryptParameters = new CipherParameters();
     *     encryptParameters.setCipherType(CipherType.AES_GCM);
     *     encryptParameters.setAuthData(ISOUtils.hex2byte("11223344556677889900AABBCCDDEEFF"));
     *     encryptParameters.setIv(ISOUtils.hex2byte("11111111111111111111111111111111"));
     *     encryptParameters.setAuthTagLen(16);
     *     byte[] data = ISOUtils.hex2byte("1212121212121212121212121212121212121212121212121212121212121212");
     *
     *     try {
     *         GCMCipherOut encryptResult = (GCMCipherOut) mCrypto.encrypt(cryptoKey, encryptParameters, data);
     *         // Handle the encrypted data: cipherOutput.getData()
     *     } catch(NSDKException e) {
     *         // Handle the exception
     *     }
     *
     * </pre>
     *
     * <p>Example 2: Using derived DUKPT key</p>
     * <pre>
     *     DUKPTDerivateKey cryptoKey = new DUKPTDerivateKey();
     *     cryptoKey.setKeyID((byte) 3);
     *     cryptoKey.setDerivateKeyType(KeyType.AES);
     *     cryptoKey.setKeyUsage(KeyUsage.DUKPT);
     *     cryptoKey.setDerivateUsage(DUKPTDerivateUsage.DATA_BOTH);
     *     cryptoKey.setDerivateKeyLen(16);
     *     CipherParameters encryptParameters = new CipherParameters();
     *     encryptParameters.setCipherType(CipherType.AES_GCM);
     *     encryptParameters.setAuthData(ISOUtils.hex2byte("11223344556677889900AABBCCDDEEFF"));
     *     encryptParameters.setIv(ISOUtils.hex2byte("11111111111111111111111111111111"));
     *     encryptParameters.setAuthTagLen(16);
     *     byte[] data = ISOUtils.hex2byte("1212121212121212121212121212121212121212121212121212121212121212");
     *     try {
     *         GCMCipherOut encryptResult = (GCMCipherOut) mCrypto.encrypt(cryptoKey, encryptParameters, data);
     *         // Handle the encrypted data: cipherOutput.getData()
     *     } catch (NSDKException e) {
     *         // Handle the exception
     *     }
     * </pre>
     *
     * @param key         <b>[Required]</b> The key used to encrypt data. see {@link SymmetricKey}. This key shall already be generated by {@link KeyManager#generateKey} before.
     *                    <ul>
     *                    <li>Key ID is required.</li>
     *                    <li>Default key usage: {@link KeyUsage#DATA}. If using derived DUKPT key, default key usage is {@link KeyUsage#DUKPT}</li>
     *                    <li>If using derived DUKPT key, the following required:
     *                    <ul>
     *                    <li>Derivate key type: see {@link KeyType}</li>
     *                    <li>Derivate key usage: {@link DUKPTDerivateUsage#DATA_ENC}, {@link DUKPTDerivateUsage#DATA_DEC}, {@link DUKPTDerivateUsage#DATA_BOTH}</li>
     *                    <li>Derivate key len: 16/24 for derived DES key, 16/24/32 for derived AES key. It shall be less than the len of AES DUKPT key.</li>
     *                    </ul>
     *                    </li>
     *                    </ul>
     * @param cipherParameters  <b>[Required]</b> Cipher parameters. See {@link CipherParameters}
     * @param data        <b>[Required]</b> The data to be encrypted. Data length shall be multiple of 16 for AES. Data maximum length shall not be more than 2000.
     * @return Encryption result, When the cipher type is GCM, the returned type is GCMCipherOut. See {@link CipherOutput} See {@link GCMCipherOut}
     * @throws NSDKException
     */
    CipherOutput encrypt(SymmetricKey key, CipherParameters cipherParameters, byte[] data) throws NSDKException;

    /**
     * Decrypts data with the key which is already exist in the PIN pad.
     *
     * <p>Example 1:</p>
     * <pre>
     *     SymmetricKey key = new SymmetricKey();
     *     key.setKeyID((byte) 2);
     *     key.setKeyUsage(KeyUsage.DATA);
     *
     *     byte[] data = ISOUtils.hex2byte("DD55F3341D5ECFF5FBC3336594620743D316FC7C3EABE42E");
     *
     *     try {
     *         CipherOutput cipherOutput =  crypto.decrypt(key, CipherType.DES_ECB, PaddingMode.NONE, null, data);
     *         // Handle the decrypted data: cipherOutput.getData()
     *     } catch(NSDKException e) {
     *         // Handle the exception
     *     }
     *
     * </pre>
     *
     * <p>Example 2: Using derived DUKPT key</p>
     * <pre>
     *     DUKPTDerivateKey desKey = new DUKPTDerivateKey();
     *     desKey.setKeyID((byte) 2);
     *     desKey.setKeyUsage(KeyUsage.DUKPT);
     *     desKey.setDerivateUsage(DUKPTDerivateUsage.DATA_DEC);
     *     desKey.setDerivateKeyType(KeyType.AES);
     *     desKey.setDerivateKeyLen(16);
     *
     *     byte[] data = ISOUtils.hex2byte("DD55F3341D5ECFF5FBC3336594620743D316FC7C3EABE42EDD55F3341D5ECFF5");
     *     try {
     *         CipherOutput cipherOutput = crypto.decrypt(desKey, CipherType.AES_DUKPT_ECB, null, null, data);
     *         // Handle the encrypted data: cipherOutput.getData()
     *     } catch (NSDKException e) {
     *         // Handle the exception
     *     }
     * </pre>
     *
     * @param key         <b>[Required]</b> The key used to decrypt data, see {@link SymmetricKey}. This key shall be generated by {@link KeyManager#generateKey} before.
     *                    <ul>
     *                    <li>Key ID is required.</li>
     *                    <li>Default key usage: {@link KeyUsage#DATA}. If using derived DUKPT key, default key usage is {@link KeyUsage#DUKPT}</li>
     *                    <li>If using derived DUKPT key, the following required:
     *                    <ul>
     *                    <li>Derivate key type: see {@link KeyType}</li>
     *                    <li>Derivate key usage: {@link DUKPTDerivateUsage#DATA_ENC}, {@link DUKPTDerivateUsage#DATA_DEC}, {@link DUKPTDerivateUsage#DATA_BOTH}</li>
     *                    <li>Derivate key len: 16/24 for derived DES key, 16/24/32 for derived AES key. It shall be less than the len of AES DUKPT key.</li>
     *                    </ul>
     *                    </li>
     *                    </ul>
     * @param cipherType  <b>[Required]</b> Cipher type. See {@link CipherType}.
     * @param paddingMode <b>[Optional]</b> Padding mode, see {@link PaddingMode}, default value is {@link PaddingMode#NONE} if this is set to null.
     * @param iv          <b>[Optional]</b> Initial vector required for CBC decryption. 8 bytes for TDES, 16 bytes for AES.
     * @param data        <b>[Required]</b> Data to be decrypted. Data length shall be multiple of 16 for AES.
     * @return Decryption result. See {@link CipherOutput}
     * @throws NSDKException
     */
    CipherOutput decrypt(SymmetricKey key, CipherType cipherType, PaddingMode paddingMode, byte[] iv, byte[] data) throws NSDKException;
    /**
     * Decrypts data with the key which is already exist in the PIN pad.
     *
     * <p>Example 1:</p>
     * <pre>
     *     SymmetricKey cryptoKey = new SymmetricKey();
     *     cryptoKey.setKeyID((byte) 3);
     *     cryptoKey.setKeyType(KeyType.AES);
     *     cryptoKey.setKeyUsage(KeyUsage.DATA);
     *     cryptoKey.setKeyLen(16);
     *     CipherParameters decryptParameters = new CipherParameters();
     *     decryptParameters.setCipherType(CipherType.AES_GCM);
     *     decryptParameters.setAuthTag(ISOUtils.hex2byte("8c99513c7f75d8f791d63cae29d4b2fc"));
     *     decryptParameters.setAuthData(ISOUtils.hex2byte("11223344556677889900AABBCCDDEEFF"));
     *     decryptParameters.setIv(ISOUtils.hex2byte("11111111111111111111111111111111"));
     *
     *     byte[] encryptedData = ISOUtils.hex2byte("44e92a9fb576ba8ad5a982806316ab8f9448cba556674ff048ce472739c37eae");
     *
     *     try {
     *         CipherOutput decryptResult = mCrypto.decrypt(cryptoKey, decryptParameters, encryptedData);
     *         // Handle the decrypted data: cipherOutput.getData()
     *     } catch(NSDKException e) {
     *         // Handle the exception
     *     }
     *
     * </pre>
     *
     * <p>Example 2: Using derived DUKPT key</p>
     * <pre>
     *     DUKPTDerivateKey cryptoKey = new DUKPTDerivateKey();
     *     cryptoKey.setKeyID((byte) 3);
     *     cryptoKey.setDerivateKeyType(KeyType.AES);
     *     cryptoKey.setKeyUsage(KeyUsage.DUKPT);
     *     cryptoKey.setDerivateUsage(DUKPTDerivateUsage.DATA_BOTH);
     *     cryptoKey.setDerivateKeyLen(16);
     *     CipherParameters decryptParameters = new CipherParameters();
     *     decryptParameters.setCipherType(CipherType.AES_GCM);
     *     decryptParameters.setAuthTag(ISOUtils.hex2byte("59b045c49c9dc5ff0855d46e3e23ecc6"));
     *     decryptParameters.setAuthData(ISOUtils.hex2byte("11223344556677889900AABBCCDDEEFF"));
     *     decryptParameters.setIv(ISOUtils.hex2byte("11111111111111111111111111111111"));
     *
     *     byte[] encryptedData = ISOUtils.hex2byte("8a2dd95afa89dd2ef534bd9f2fae262782a54b6163df91d217f1b8b4afe4d545");
     *     try {
     *         CipherOutput decryptResult = mCrypto.decrypt(cryptoKey, decryptParameters, encryptedData);
     *         // Handle the encrypted data: cipherOutput.getData()
     *     } catch (NSDKException e) {
     *         // Handle the exception
     *     }
     * </pre>
     *
     * @param key         <b>[Required]</b> The key used to decrypt data, see {@link SymmetricKey}. This key shall be generated by {@link KeyManager#generateKey} before.
     *                    <ul>
     *                    <li>Key ID is required.</li>
     *                    <li>Default key usage: {@link KeyUsage#DATA}. If using derived DUKPT key, default key usage is {@link KeyUsage#DUKPT}</li>
     *                    <li>If using derived DUKPT key, the following required:
     *                    <ul>
     *                    <li>Derivate key type: see {@link KeyType}</li>
     *                    <li>Derivate key usage: {@link DUKPTDerivateUsage#DATA_ENC}, {@link DUKPTDerivateUsage#DATA_DEC}, {@link DUKPTDerivateUsage#DATA_BOTH}</li>
     *                    <li>Derivate key len: 16/24 for derived DES key, 16/24/32 for derived AES key. It shall be less than the len of AES DUKPT key.</li>
     *                    </ul>
     *                    </li>
     *                    </ul>
     * @param cipherParameters  <b>[Required]</b> Cipher parameters. See {@link CipherParameters}
     * @param data        <b>[Required]</b> Data to be decrypted. Data length shall be multiple of 16 for AES.
     * @return Decryption result. See {@link CipherOutput}
     * @throws NSDKException
     */
    CipherOutput decrypt(SymmetricKey key, CipherParameters cipherParameters, byte[] data) throws NSDKException;

    /**
     * Encrypts data with the asymmetric key which is already exist in the PIN pad.
     *
     * <p>Example:</p>
     * <pre>
     *     AsymmetricKey key = new AsymmetricKey();
     *     key.setKeyID((byte) 3);
     *     key.setKeyUsage(AsymKeyUsage.DATA);
     *     key.setKeyType(AsymKeyType.RSA);
     *
     *     AsymAlgorithmParameters parameters = new AsymAlgorithmParameters();
     *     parameters.setMessageDigestType(MessageDigestType.SHA256);
     *     parameters.setEncodingMode(AsymEncodingMode.PKCS_V21);
     *     parameters.setCryptoMode(AsymCryptoMode.PUBLIC);
     *
     *     byte[] data = ISOUtils.hex2byte("0102030405060708090A0B0C0D0E0F");
     *
     *     try {
     *         byte[] result = crypto.encryptAsym(key, parameters, data);
     *     } catch (NSDKException e) {
     *         // Handle the error
     *     }
     * </pre>
     *
     * @param key                 <b>[Required]</b> The key used to encrypt data, see {@link AsymmetricKey}. This key shall be generated by {@link KeyManager#generateKey} before.
     *                            <ul>
     *                            <li><b>[Required]</b> Key ID</li>
     *                            <li><b>[Required]</b> Key usage</li>
     *                            <li><b>[Required]</b> Key type</li>
     *                            </ul>
     * @param algorithmParameters <b>[Required]</b> Algorithm parameters, see {@link AsymAlgorithmParameters}.
     *                            <ul>
     *                            <li><b>[Optional]</b> Message digest type is required when encoding mode is not {@link AsymEncodingMode#PKCS_V15}.</li>
     *                            <li><b>[Required]</b> Encoding mode</li>
     *                            <li><b>[Required]</b> Crypto mode</li>
     *                            </ul>
     * @param data                <b>[Required]</b> Data to be encrypted.
     * @return Encryption result.
     * @throws NSDKException
     */
    byte[] encryptAsym(AsymmetricKey key, AsymAlgorithmParameters algorithmParameters, byte[] data) throws NSDKException;

    /**
     * Decrypts data with the asymmetric key which is already exist in the PIN pad.
     *
     * <p>Example:</p>
     * <pre>
     *     AsymmetricKey key = new AsymmetricKey();
     *     key.setKeyID((byte) 3);
     *     key.setKeyUsage(AsymKeyUsage.DATA);
     *     key.setKeyType(AsymKeyType.RSA);
     *
     *     AsymAlgorithmParameters parameters = new AsymAlgorithmParameters();
     *     parameters.setMessageDigestType(MessageDigestType.SHA256);
     *     parameters.setEncodingMode(AsymEncodingMode.PKCS_V21);
     *     parameters.setCryptoMode(AsymCryptoMode.PUBLIC);
     *
     *     try {
     *         byte[] decryptedData = crypto.decryptAsym(key, parameters, encryptedData);
     *     } catch (NSDKException e) {
     *         // Handle the error.
     *     }
     * </pre>
     *
     * @param key                 <b>[Required]</b> The key used to decrypt data, see {@link AsymmetricKey}. This key shall be generated by {@link KeyManager#generateKey} before.
     *                            <ul>
     *                            <li><b>[Required]</b> Key ID</li>
     *                            <li><b>[Required]</b> Key usage</li>
     *                            <li><b>[Required]</b> Key type</li>
     *                            </ul>
     * @param algorithmParameters <b>[Required]</b> Algorithm parameters, see {@link AsymAlgorithmParameters}.
     *                            <ul>
     *                            <li><b>[Optional]</b> Message digest type is required when encoding mode is not {@link AsymEncodingMode#PKCS_V15}.</li>
     *                            <li><b>[Required]</b> Encoding mode</li>
     *                            <li><b>[Required]</b> Crypto mode</li>
     *                            </ul>
     * @param data                <b>[Required]</b> Data to be decrypted.
     * @return Decryption result.
     * @throws NSDKException
     */
    byte[] decryptAsym(AsymmetricKey key, AsymAlgorithmParameters algorithmParameters, byte[] data) throws NSDKException;

    /**
     * Gets signature data.
     *
     * <p>Example:</p>
     * <pre>
     *      AsymmetricKey key = new AsymmetricKey();
     *      key.setKeyID((byte) 10);
     *      key.setKeyUsage(AsymKeyUsage.AUTH);
     *      key.setKeyType(AsymKeyType.RSA);
     *
     *      AsymAlgorithmParameters parameters = new AsymAlgorithmParameters();
     *      parameters.setMessageDigestType(MessageDigestType.SHA256);
     *      parameters.setEncodingMode(AsymEncodingMode.PKCS_V15);
     *
     *      String originalString = "12345678";
     *      byte[] hash = null;
     *      byte[] signedData = null;
     *
     *      try {
     *          MessageDigest digest = MessageDigest.getInstance("SHA-256");
     *          hash = digest.digest(originalString.getBytes());
     *          signedData = crypto.signAsym(key, parameters, hash);
     *      } catch (NoSuchAlgorithmException e) {
     *          // Failed to get SHA256 message digest instance.
     *      } catch (NSDKException e) {
     *          // Handle the error.
     *      }
     * </pre>
     *
     * @param key                 <b>[Required]</b> The key used to sign data.
     *                            <ul>
     *                            <li><b>[Required]</b> Key ID</li>
     *                            <li><b>[Required]</b> Key usage</li>
     *                            <li><b>[Required]</b> Key type</li>
     *                            </ul>
     * @param algorithmParameters Algorithm parameters, see {@link AsymAlgorithmParameters}.
     *                            <ul>
     *                            <li><b>[Required]</b> Message digest type</li>
     *                            <li><b>[Required]</b> Encoding mode</li>
     *                            </ul>
     * @param hash                <b>[Required]</b> Hash data to be signed.
     * @return Signed data.
     * @throws NSDKException
     */
    byte[] signAsym(AsymmetricKey key, AsymAlgorithmParameters algorithmParameters, byte[] hash) throws NSDKException;

    /**
     * Verifies if the signature is correct.
     *
     * <p>Example:</p>
     * <pre>
     *      AsymmetricKey key = new AsymmetricKey();
     *      key.setKeyID((byte) 10);
     *      key.setKeyUsage(AsymKeyUsage.AUTH);
     *      key.setKeyType(AsymKeyType.RSA);
     *
     *      AsymAlgorithmParameters parameters = new AsymAlgorithmParameters();
     *      parameters.setMessageDigestType(MessageDigestType.SHA256);
     *      parameters.setEncodingMode(AsymEncodingMode.PKCS_V15);
     *
     *      try {
     *          crypto.verifyAsym(key, parameters, hash, signedData);
     *      } catch (NoSuchAlgorithmException e) {
     *          // Failed to get SHA256 message digest instance.
     *      } catch (NSDKException e) {
     *          // Handle the error.
     *      }
     * </pre>
     *
     * @param key                 <b>[Required]</b> The key used to verify signed data, see {@link AsymmetricKey}.
     *                            <ul>
     *                            <li><b>[Required]</b> Key ID</li>
     *                            <li><b>[Required]</b> Key usage</li>
     *                            <li><b>[Required]</b> Key type</li>
     *                            </ul>
     * @param algorithmParameters Algorithm parameters, see {@link AsymAlgorithmParameters}.
     *                            <ul>
     *                            <li><b>[Required]</b> Message digest type</li>
     *                            <li><b>[Required]</b> Encoding mode</li>
     *                            </ul>
     * @param hash                <b>[Required]</b> Hash data.
     * @param signedData          <b>[Required]</b> Signed data to verify.
     * @throws NSDKException
     */
    void verifyAsym(AsymmetricKey key, AsymAlgorithmParameters algorithmParameters, byte[] hash, byte[] signedData) throws NSDKException;

    /**
     * Gets random data.
     *
     * <p>Example:</p>
     * <pre>
     *     // Get random data with length 16.
     *     try {
     *         byte[] randomOut = crypto.getRandom(16);
     *     } catch(NSDKException e) {
     *         // Handle the exception
     *     }
     * </pre>
     *
     * @param len <b>[Required]</b> Length of random data, shall be >0.
     * @return Random data.
     * @throws NSDKException
     */
    byte[] getRandom(int len) throws NSDKException;

    /**
     * Initials CSR handle and sets the basic information.
     * @param parameters  <b>[Required]</b> The CSR parameters, see {@link CSRParameters}.
     * @throws NSDKException
     */
    void initCSR(CSRParameters parameters) throws NSDKException;

    /**
     * Generates CSR file data.
     * @param fileType  <b>[Required]</b> The CSR file type to be generated. See {@link CSRFileType}.
     * @return The according file type CSR data.
     * @throws NSDKException
     */
    byte[] generateCSR(CSRFileType fileType) throws NSDKException;

    /**
     * Releases CSR handle.
     * @throws NSDKException
     */
    void releaseCSR() throws NSDKException;

    /**
     * Creates the cryptogram block for connection with server with crypto key, exported session key and component secret key from server.
     * @param cryptoKey           <b>[Required]</b> The asymmetrical key for crypto. Details see {@link AsymmetricKey}.
     *                            <ul>
     *                            <li><b>[Required]</b>{@link AsymmetricKey#keyID} is required.</li>
     *                            <li><b>[Required]</b>{@link AsymmetricKey#keyType} is required.</li>
     *                            <li><b>[Required]</b>{@link AsymmetricKey#keyUsage} is required.</li>
     *                            </ul>
     * @param sessionKey          <b>[Required]</b> The exported session key, currently only supported {@link SymmetricKey}.
     * @param componentSecretKey  <b>[Required]</b> The component secret key injected with server information.
     * @param cryptogramInfo      <b>[Required]</b> The information used for cryptogram processing. Details see {@link CryptogramInfo}
     *                            <ul>
     *                            <li><b>[Required]</b> {@link CryptogramInfo#prefixInfo} is required. This is the prefix of the information to be encrypted.</li>
     *                            <li><b>[Required]</b> {@link CryptogramInfo#suffixInfo} is required. This is the suffix of the information to be encrypted.</li>
     *                            <li><b>[Required]</b> {@link CryptogramInfo#encodingMode} is required. This is the encoding mode for the asymmetrical encryption, see {@link AsymEncodingMode}.</li>
     *                            <li><b>[Required]</b> {@link CryptogramInfo#messageDigestType} is required. This is the message digest type for the encryption data, see {@link com.newland.nsdk.core.api.common.crypto.MessageDigestType}.</li>
     *                            <li><b>[Optional]</b> {@link CryptogramInfo#additionalData} is optional, which is reserved for the further use.</li>
     *                            </ul>
     * @return The cryptogram information for the connection to server.
     * @throws NSDKException
     */
    byte[] createCryptogram(AsymmetricKey cryptoKey, Key sessionKey, Key componentSecretKey, CryptogramInfo cryptogramInfo) throws NSDKException;

     /**
     * Verifies cert data with target CA cert data.
     * @param isCACertPath  <b>[Required]</b> Whether is input CA cert path, when it is true, it means input CA cert path, otherwise CA cert data.
     * @param caData        <b>[Required]</b> CA cert path or CA cert data
     * @param certData      <b>[Required]</b> Certificate data to be verified.
     * @return The public key of the verified cert.
     * @throws NSDKException
     */
    byte[] verifyCert(boolean isCACertPath, String caData, byte[] certData) throws NSDKException;
}
