plugins {
    id 'com.android.library'
}


android {
    namespace 'com.hudou.autotest'
    compileSdk 34

    defaultConfig {
        //applicationId "com.hudou.autotest"
        minSdk 29
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets{
        main{
            jniLibs.srcDirs = ['src/main/jniLibs', 'libs']
        }
    }

    buildFeatures {
        viewBinding = true
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.navigation:navigation-runtime:2.8.8'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')
    annotationProcessor 'com.google.auto.service:auto-service:1.0.1'
    implementation 'com.google.auto.service:auto-service-annotations:1.0.1'
    implementation 'com.alibaba:fastjson:1.2.75'
    implementation 'com.google.code.gson:gson:2.8.6'

    implementation 'androidx.recyclerview:recyclerview:1.3.0'

    implementation 'org.reflections:reflections:0.9.10'
    implementation 'org.slf4j:slf4j-api:1.7.30'
    implementation 'commons-cli:commons-cli:1.4'

    api 'net.sourceforge.jexcelapi:jxl:2.6.12'
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"


}

configurations.all {
    resolutionStrategy {
        force 'com.google.guava:guava:18.0'
        exclude group: 'com.google.guava', module: 'listenablefuture'
    }
}
