apply plugin: 'com.android.application'

android {
    signingConfigs {
        debug {
            v1SigningEnabled true
            v2SigningEnabled false
        }

        release {
//            storeFile file('..\\nsdkkeystore.jks')
//            storePassword '123456'
//            keyAlias 'nsdk'
//            keyPassword '123456'
            v1SigningEnabled true
            v2SigningEnabled false
        }
    }
    compileSdkVersion 28
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
    lintOptions {
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

repositories {
    flatDir{
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:recyclerview-v7:28.0.0'

    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'org.greenrobot:eventbus:3.2.0'

    implementation 'com.google.zxing:core:3.3.3'

//    implementation(name: 'Newland-NSDK-2.1.0a', ext: 'aar')

//    implementation project(path: ':nsdk')
//    implementation project(path: ':nsdkplugincard')
}

task generateSources(type: Copy) {
    from 'nsdkdemo/src/main/java/com/newland/nsdkdemo/fragment'
    into "../nsdkdemo/src/main/java/com/newland/nsdkdemo/fragment"
    include 'Ext*.java'
}

//def signToolPath = "F:\\pkgNLD"
//def tmpNameOut = "-unsigned.apk"  //
//gradle.buildFinished {
//    println("=====================Enter buildFinished=======================")
//    android.applicationVariants.all { variant ->
//        if (variant.buildType.name == 'debug') {
//            String outputedFilename = ""
//            String TARGET_DIR = ""
//            variant.outputs.each { output ->
//                def outputFile = output.outputFile
//                println("> devsignTask :app:   ======================================= "  )
//                if (outputFile != null && outputFile.name.endsWith('.apk')) {
//                    outputedFilename = outputFile.name
//                    println("> devsignTask :app: outputFile File Name is : " + outputedFilename)
//                    TARGET_DIR = outputFile.parent +"\\"
//                }
//            }
//            println("> devsignTask :app: TARGET_DIR : " + TARGET_DIR)
//            def devBuildTask = tasks.create(name: "devsignTask", type: Exec, description: 'for newland dev apk pack') {
//                def devBuildFile = file(TARGET_DIR + outputedFilename);
//                def fileName = devBuildFile.getName();
//                println("> devsignTask :app: unsigned File Name : " + fileName)
//                if (!devBuildFile.exists()) {
//                    println("> devsignTask :app: unsigned File not found : " + fileName)
//                    return
//                }
//                def tmpfileName = fileName.substring(0, fileName.length()-4) +tmpNameOut;
//
//                copy {
//                    println("> devsignTask :app: start copy file " )
//                    from(TARGET_DIR) {
//                        include '**/*.apk'
//                        exclude '**/*.json'
//                    }
//                    into TARGET_DIR
//                    rename(fileName, tmpfileName )
//                }
//
//                delete {
//                    delete devBuildFile
//                }
//                def tempFile = file(TARGET_DIR + tmpfileName);
//                if (!tempFile.exists()) {
//                    println("> devsignTask :app:--- temp apk not found  --- ")
//                    println("> devsignTask :app: Pack failed ... ")
//                    return
//                }
//                exec {
//                    println("> devsignTask :app:--- Start Dev Sign Task --- ")
//                    println tempFile.getPath()
//                    def appWorkingDir = workingDir
//                    println "> devsignTask :app: The current directory is: "
//                    println appWorkingDir
//                    workingDir signToolPath
//                    println "> devsignTask :app: The SignTool directory is: "
//                    println workingDir
//                    commandLine 'cmd', '/c', "upt.exe -i ${tempFile.getPath()} -o  ${TARGET_DIR}${fileName}"
//                    println commandLine
//                    println("> devsignTask :app: Packing......")
//                }
//                delete {
//                    if (!tempFile.exists()) {
//                        println("> devsignTask :app: tempFile not found  ")
//                    } else {
//                        println tempFile.getAbsoluteFile();
//                        delete tempFile
//                        println("> devsignTask :app: deleted the temp file")
//                    }
//                }
//            }
//            devBuildTask.mustRunAfter variant.getAssembleProvider()
//        }
//    }
//    println("=====================Exit buildFinished=======================")
//}

