package com.newland.forth.module.crypto.cipher;

/**
 * @Description
 * @Author wuhh
 * @Date 2023/4/14
 */
public enum EM_SEC_DUKPT_DERIVATE_USAGE {
    DUKPT_DERIVATE_NONE,
    DUKPT_DERIVATE_KEK,
    DUKPT_DERIVATE_PIN,
    DUKPT_DERIVATE_MAC_GEN,
    DUKPT_DERIVATE_MAC_VERIFY,
    DUKPT_DERIVATE_MAC_BOTH,
    DUKPT_DERIVATE_DATA_ENC,
    DUKPT_DERIVATE_DATA_DEC,
    DUKPT_DERIVATE_DATA_BOTH,
    DUKPT_DERIVATE_DERIVATEKEY,
    DUKPT_DERIVATE_DERIVATEKEY_INITIAL,
}
