plugins {
    id 'com.android.library'
}

apply from: 'version.gradle'

android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 26
        versionCode appVersionCode
        versionName appVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        setProperty("archivesBaseName", "NSDK-Plugin-Card-$versionName")
    }

    buildTypes {
        debug {
            minifyEnabled false
        }

        release {
            minifyEnabled true
            zipAlignEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

repositories {
    flatDir{
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')

    implementation 'com.android.support:appcompat-v7:28.0.0'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation project(path: ':nsdkcommon')
    implementation project(path: ':nsdkexternal')
    implementation project(path: ':nsdk')
}

def TEMP_PATH = "build/temp"
def TEMP_UNZIP_PATH = "build/temp/aar"
def JAR_NAME = "classes.jar"
def DESTINATION_PATH = "build"
def NEW_NAME = "NSDK-Plugin-Card-"+appVersionName+".jar"

task unzipAar(dependsOn: ['assembleRelease'], type: Copy) {
    def zipFile = file("build/outputs/aar/NSDK-Plugin-Card-"+appVersionName+"-release.aar")
    def outputDir = file(TEMP_UNZIP_PATH)
    FileTree fileTree = zipTree(zipFile)
    from fileTree
    into outputDir
}

task addSourcesToClassesJar(dependsOn: ['unzipAar'], type: Jar) {
    archiveName JAR_NAME
    destinationDir file(TEMP_PATH)
    from zipTree(TEMP_UNZIP_PATH + "/" + JAR_NAME)
    from ("src/main/java"){
        include('com/newland/nsdk/plugin/card/api/**/*.java')
    }
}

task buildJar(dependsOn: ['addSourcesToClassesJar'], type: Copy) {
    from(TEMP_PATH+"/" +JAR_NAME)
    into(DESTINATION_PATH)
    rename(JAR_NAME, NEW_NAME)
}