package com.newland.nsdk.core.api.common.emv;

/**
 * Constant definition for the ErrorCode class.
 */
public enum EMVErrorMessage {


    Error_MESSAGE_EMV_ERR_READCONFIG(EMVErrorCode.EMV_ERR_READCONFIG, "Failed to read aid configuration"),
    Error_MESSAGE_EMV_ERR_READAIDLIST(EMVErrorCode.EMV_ERR_READAIDLIST, "Failed to read aid list"),
    Error_MESSAGE_EMV_ERR_POWERUP(EMVErrorCode.EMV_ERR_POWERUP, "IC card unable to power on"),
    Error_MESSAGE_EMV_ERR_NOTSUPPORT(EMVErrorCode.EMV_ERR_NOTSUPPORT, "IC card not support instruction"),
    Error_MESSAGE_EMV_ERR_APPBLOCK(EMVErrorCode.EMV_ERR_APPBLOCK, "Application lock"),
    Error_MESSAGE_EMV_ERR_FINDAPP(EMVErrorCode.EMV_ERR_FINDAPP, "Can't find supported applications"),
    Error_MESSAGE_EMV_ERR_Cancel(EMVErrorCode.EMV_ERR_CANCEL, "EMVL2 ErrorCode,Quit the transaction"),
    Error_MESSAGE_EMV_ERR_SELECTAPP(EMVErrorCode.EMV_ERR_SELECTAPP, "Application selection failed"),
    Error_MESSAGE_EMV_ERR_APPINIT(EMVErrorCode.EMV_ERR_APPINIT, "Application initialization failed"),
    Error_MESSAGE_EMV_ERR_READAPPDATA(EMVErrorCode.EMV_ERR_READAPPDATA, "Failed to read application data"),
    Error_MESSAGE_EMV_ERR_OFFAUTH(EMVErrorCode.EMV_ERR_OFFAUTH, "Offline data authentication failed"),
    Error_MESSAGE_EMV_ERR_PROCESSLIMIT(EMVErrorCode.EMV_ERR_PROCESSLIMIT, "Process limit failed"),
    Error_MESSAGE_EMV_ERR_CARDVERIFY(EMVErrorCode.EMV_ERR_CARDVERIFY, "Cardholder authentication failed"),
    Error_MESSAGE_EMV_ERR_TERMRISKMANAGE(EMVErrorCode.EMV_ERR_TERMRISKMANAGE, "Terminal risk management failed"),
    Error_MESSAGE_EMV_ERR_TERMACTANALYZE(EMVErrorCode.EMV_ERR_TERMACTANALYZE, "Terminal behavior analysis failed"),
    Error_MESSAGE_EMV_ERR_NOTSUPPORTSERVICE(EMVErrorCode.EMV_ERR_NOTSUPPORTSERVICE, "Unsupported service"),
    Error_MESSAGE_EMV_ERR_NORANDNUM(EMVErrorCode.EMV_ERR_NORANDNUM, "No random number"),
    Error_MESSAGE_EMV_ERR_CARDBLOCK(EMVErrorCode.EMV_ERR_CARDBLOCK, "Card lock"),
    Error_MESSAGE_EMV_ERR_COMPLETION(EMVErrorCode.EMV_ERR_COMPLETION, "GEN AC execution failed"),
    Error_MESSAGE_EMV_ERR_SAVECONFIG(EMVErrorCode.EMV_ERR_SAVECONFIG, "Save key configuration failed"),
    Error_MESSAGE_EMV_ERR_RF_PREPROCESS(EMVErrorCode.EMV_ERR_RF_PREPROCESS, "RF card preprocessing failed"),
    Error_MESSAGE_EMV_ERR_TIMEOUT(EMVErrorCode.EMV_ERR_TIMEOUT, "Operation timeout"),
    Error_MESSAGE_EMV_ERR_RF_GETICC(EMVErrorCode.EMV_ERR_RF_GETICC, "Inserted IC card detected during RF card finder"),
    Error_MESSAGE_EMV_ERR_AID_COUNT_EXCEED(EMVErrorCode.EMV_ERR_AID_COUNT_EXCEED, "Too many AIDs"),
    Error_MESSAGE_EMV_ERR_AID_EMPTY(EMVErrorCode.EMV_ERR_AID_EMPTY, "empty aid"),


    Error_MESSAGE_FILEERR_BASE(EMVErrorCode.FILEERR_BASE, "AID configuration file benchmark error code"),
    Error_MESSAGE_FILE_OPEN_FILE(EMVErrorCode.FILE_OPEN_FILE, "AID configuration file open failed"),
    Error_MESSAGE_FILE_READ_FILE(EMVErrorCode.FILE_READ_FILE, "AID configuration file read failed"),
    Error_MESSAGE_FILE_WRITE_FILE(EMVErrorCode.FILE_WRITE_FILE, "AID configuration file write failed"),
    Error_MESSAGE_FILE_AID_VERSION(EMVErrorCode.FILE_AID_VERSION, "AID configuration file version error"),
    Error_MESSAGE_FILE_GETTLVDATA_NOEXIST(EMVErrorCode.FILE_GETTLVDATA_NOEXIST, "AID configuration file Can't get the required AID"),
    Error_MESSAGE_FILE_AIDERR_PARSE(EMVErrorCode.FILE_AIDERR_PARSE, "AID configuration file Tlv data parsing failed"),
    Error_MESSAGE_FILE_AIDERR_API(EMVErrorCode.FILE_AIDERR_API, "Use wrong API interface"),


    Error_MESSAGE_ICCERR_BASE(EMVErrorCode.ICCERR_BASE, "ICC Apdu benchmark error code"),
    Error_MESSAGE_APDU_DATA_NULL(EMVErrorCode.APDU_DATA_NULL, "apdu interactive data is empty"),
    Error_MESSAGE_COREERR_BASE(EMVErrorCode.COREERR_BASE, "Kernel basic operation benchmark error code"),
    Error_MESSAGE_COREERR_GETTIME(EMVErrorCode.COREERR_GETTIME, "Get POS time error"),
    Error_MESSAGE_COREERR_READFINALPARAM(EMVErrorCode.COREERR_READFINALPARAM, "READ FINAL PARAM error"),
    Error_MESSAGE_COREERR_GETUNPNUM(EMVErrorCode.COREERR_GETUNPNUM, "Get random number error"),
    Error_MESSAGE_BUFERR_BASE(EMVErrorCode.BUFERR_BASE, "Data cache benchmark error code"),
    Error_MESSAGE_BUFERR_BUFOVER(EMVErrorCode.BUFERR_BUFOVER, "Data buffer not enough storage"),
    Error_MESSAGE_BUFERR_OBJDUP(EMVErrorCode.BUFERR_OBJDUP, "The label is unique and cannot be overwritten if the length is greater than zero"),
    Error_MESSAGE_BUFERR_MALLOCFAIL(EMVErrorCode.BUFERR_MALLOCFAIL, "Dynamic memory allocation failed"),


    Error_MESSAGE_SELERR_BASE(EMVErrorCode.SELERR_BASE, "Application select benchmark error code"),
    Error_MESSAGE_SEL_USE_AIDLIST(EMVErrorCode.SEL_USE_AIDLIST, "application select AID list failed"),
    Error_MESSAGE_SEL_QUIT(EMVErrorCode.SEL_QUIT, "Application select cancle the transaction"),
    Error_MESSAGE_SEL_FCIFMTERR(EMVErrorCode.SEL_FCIFMTERR, "FCI data format error"),
    Error_MESSAGE_SEL_FCINO6F(EMVErrorCode.SEL_FCINO6F, "FCI data without 6F"),
    Error_MESSAGE_SEL_FCINO84(EMVErrorCode.SEL_FCINO84, "FCI data without 84"),
    Error_MESSAGE_SEL_FCINOA5(EMVErrorCode.EMV_ERR_READCONFIG, "FCI data without A5"),
    Error_MESSAGE_SEL_POSERR9F38(EMVErrorCode.SEL_POSERR9F38, "FCI data error 9F38"),
    Error_MESSAGE_SEL_BF0CDUP(EMVErrorCode.SEL_BF0CDUP, "FCI data tagBF0C repeat"),
    Error_MESSAGE_SEL_FALLBACK(EMVErrorCode.SEL_FALLBACK, "Application selection return transaction"),
    Error_MESSAGE_SEL_FCI50DUP(EMVErrorCode.SEL_FCI50DUP, "FCI data tag50 repeat"),
    Error_MESSAGE_SEL_FCIDUP(EMVErrorCode.SEL_FCIDUP, "FCI data repeat"),
    Error_MESSAGE_SEL_TLV_ERR(EMVErrorCode.SEL_TLV_ERR, "FCI data TLV parsing failed"),
    Error_MESSAGE_SEL_NO6F(EMVErrorCode.SEL_NO6F, "FCI data without tag 6F"),
    Error_MESSAGE_SEL_NO84(EMVErrorCode.SEL_NO84, "FCI data without 84"),
    Error_MESSAGE_SEL_NOA5(EMVErrorCode.SEL_NOA5, "FCI data without A5"),
    Error_MESSAGE_SEL_TAG_SEQERR(EMVErrorCode.SEL_TAG_SEQERR, "The tag sequence is wrong. For example, tag '84' should be placed before tag 'A5'"),
    Error_MESSAGE_SEL_NOBF0C(EMVErrorCode.SEL_NOBF0C, "FCI data without tag BF0C"),
    Error_MESSAGE_SEL_BFOC_DATAERR(EMVErrorCode.SEL_BFOC_DATAERR, "FCI data tag 8F0C parsing failed"),
    Error_MESSAGE_SEL_AID_DIFF_DFNAME(EMVErrorCode.SEL_AID_DIFF_DFNAME, "(final selection, return DF Name  not the same as the AID of command"),
    Error_MESSAGE_SEL_ERR_TRANSTYPE(EMVErrorCode.SEL_ERR_TRANSTYPE, "Wrong transaction type"),
    Error_MESSAGE_SEL_PPSE_ERROR(EMVErrorCode.SEL_PPSE_ERROR, "PPSE command returned failure"),
    Error_MESSAGE_SEL_NEXT_AID(EMVErrorCode.SEL_NEXT_AID, "Select the next AID"),
    Error_MESSAGE_SEL_DISCOVER_ZIP_AID(EMVErrorCode.SEL_DISCOVER_ZIP_AID, "Discover zip aid special treatment for ppse"),
    Error_MESSAGE_SEL_NO84VALUE(EMVErrorCode.SEL_NO84VALUE, "FCI data without the value of tag 84"),
    Error_MESSAGE_SEL_DPASNOHAVEZIPAID(EMVErrorCode.SEL_DPASNOHAVEZIPAID, "DPAS ppse only returns dpas aid does not return zip aid"),
    Error_MESSAGE_SEL_AMT_OVER_CLSS(EMVErrorCode.SEL_AMT_OVER_CLSS, "contactless transaction amount  exceeds limit"),
    Error_MESSAGE_SEL_AMTZERO_CLSS_NOT_ALLOW(EMVErrorCode.SEL_AMTZERO_CLSS_NOT_ALLOW, "when Amount zero, Set the Contactless Application Not Allowed"),
    Error_MESSAGE_SEL_AMTZERO_CLSS_OFFLINE_OLY(EMVErrorCode.SEL_AMTZERO_CLSS_OFFLINE_OLY, "when Amount zero, shall set go online, but terminal offline only"),
    Error_MESSAGE_SEL_BANCOMATLEGACY_AID(EMVErrorCode.SEL_BANCOMATLEGACY_AID, "Bancomat Legacy aid special treatment for ppse"),
    Error_MESSAGE_SEL_TAG61_INVALID(EMVErrorCode.SEL_TAG61_INVALID, "Application selection tag61 is invalid"),
    Error_MESSAGE_SEL_TAG4F_INVALID(EMVErrorCode.SEL_TAG4F_INVALID, "Application selection tag4F is invalid"),
    Error_MESSAGE_SEL_TAG4F_PARTIAL(EMVErrorCode.SEL_TAG4F_PARTIAL, "Application selection tag4F partial matching incomplete"),
    Error_MESSAGE_SEL_FCI_FMTERR(EMVErrorCode.SEL_FCI_FMTERR, "JCB FCI format error"),
    Error_MESSAGE_SEL_FCIERR84(EMVErrorCode.SEL_FCIERR84, "JCB FCI 84 error"),
    Error_MESSAGE_SEL_FCINO50(EMVErrorCode.SEL_FCINO50, "FCI without 50"),
    Error_MESSAGE_SEL_FCINO9F38(EMVErrorCode.SEL_FCINO9F38, "JCB FCI without 9F38"),
    Error_MESSAGE_SEL_FCIEMPTY9F28(EMVErrorCode.SEL_FCIEMPTY9F28, "JCB FCI 9F28 is empty"),
    Error_MESSAGE_SEL_FCI_ILLEGALTAG(EMVErrorCode.SEL_FCI_ILLEGALTAG, "JCB FCI failed to find proprietary data"),
    Error_MESSAGE_SEL_FCI_REV_LEGACY(EMVErrorCode.SEL_FCI_REV_LEGACY, "JCB Torn transaction is Legacy Mode"),
    Error_MESSAGE_SEL_FCI_MANDATAMISS(EMVErrorCode.SEL_FCI_MANDATAMISS, "MCCS enforces data loss"),
    Error_MESSAGE_SEL_FCINO87(EMVErrorCode.SEL_FCINO87, "FCI without tag 87"),
    Error_MESSAGE_SEL_FCI9F38LENWRONG(EMVErrorCode.SEL_FCI9F38LENWRONG, "FCI data 9F38 length wrong"),
    Error_MESSAGE_SEL_FCIPARAMERROR(EMVErrorCode.SEL_FCIPARAMERROR, "FCI format error"),
    Error_MESSAGE_SEL_FINALSEL_6300(EMVErrorCode.SEL_FINALSEL_6300, "Application selection returns 6300,State of non-volatile memory changed; authentication failed"),
    Error_MESSAGE_SEL_FINALSEL_63C1(EMVErrorCode.SEL_FINALSEL_63C1, "Application selection returns 63C1"),
    Error_MESSAGE_SEL_FINALSEL_6983(EMVErrorCode.SEL_FINALSEL_6983, "Application selection returns 6983,Command not allowed; authentication method blocked"),
    Error_MESSAGE_SEL_FINALSEL_6984(EMVErrorCode.SEL_FINALSEL_6984, "Application selection returns 6984,Command not allowed; reference data not usable"),
    Error_MESSAGE_SEL_FINALSEL_6985(EMVErrorCode.SEL_FINALSEL_6985, "Application selection returns 6985,Command not allowed; conditions of use not satisfied"),
    Error_MESSAGE_SEL_FINALSEL_6A82(EMVErrorCode.SEL_FINALSEL_6A82, "Application selection returns 6A82,Wrong parameters P1-P2; file or application not found"),
    Error_MESSAGE_SEL_FINALSEL_6A83(EMVErrorCode.SEL_FINALSEL_6A83, "Application selection returns 6A83,Wrong parameters P1-P2; record not found"),
    Error_MESSAGE_SEL_FINALSEL_6A88(EMVErrorCode.SEL_FINALSEL_6A88, "Application selection returns 6A88,Reference data (data objects) not found)"),
    Error_MESSAGE_SEL_FINALSEL_6400(EMVErrorCode.SEL_FINALSEL_6400, "Application selection returns 6400"),
    Error_MESSAGE_SEL_FINALSEL_6500(EMVErrorCode.SEL_FINALSEL_6500, "Application selection returns 6500"),
    Error_MESSAGE_SEL_FINALSEL_9001(EMVErrorCode.SEL_FINALSEL_9001, "Application selection returns 9001"),
    Error_MESSAGE_SEL_L1_FAIL(EMVErrorCode.SEL_L1_FAIL, "Application selection apdu communication failed"),
    Error_MESSAGE_SEL_L1_ACTIVE(EMVErrorCode.SEL_L1_ACTIVE, "Active card failed"),
    Error_MESSAGE_SEL_FCIPDOL9F02WRONG(EMVErrorCode.SEL_FCIPDOL9F02WRONG, "FCI PDOL 9F02 Lenth Wrong"),
    Error_MESSAGE_SEL_FCIPDOL9AWRONG(EMVErrorCode.SEL_FCIPDOL9AWRONG, "FCI PDOL 9A Lenth Wrong"),
    Error_MESSAGE_SEL_FCIPDOL9CWRONG(EMVErrorCode.SEL_FCIPDOL9CWRONG, "FCI PDOL 9C Lenth Wrong"),
    Error_MESSAGE_SEL_FCIPDOL9F37WRONG(EMVErrorCode.SEL_FCIPDOL9F37WRONG, "FCI PDOL 9F37 Lenth Wrong"),
    Error_MESSAGE_SEL_FCIPDOL9F35WRONG(EMVErrorCode.SEL_FCIPDOL9F35WRONG, "FCI PDOL 9F35 Lenth Wrong"),
    Error_MESSAGE_SEL_FCIPDOL9F66WRONG(EMVErrorCode.SEL_FCIPDOL9F66WRONG, "FCI PDOL 9F66 Lenth Wrong"),
    Error_MESSAGE_KA_ERR_BASE(EMVErrorCode.KA_ERR_BASE, "JCB benchmark error code"),
    Error_MESSAGE_KA_CONFIG_EMPTY(EMVErrorCode.KA_CONFIG_EMPTY, "JCB configured to be empty"),
    Error_MESSAGE_KA_LEGACY_NOTSUPPORTED(EMVErrorCode.KA_LEGACY_NOTSUPPORTED, "JCB Legacy mode is not supported"),


    Error_MESSAGE_INITERR_BASE(EMVErrorCode.INITERR_BASE, "Application initialization benchmark error code"),
    Error_MESSAGE_INITERR_DOLPACKET(EMVErrorCode.INITERR_DOLPACKET, "Application initialization PDOL packaging failed"),
    Error_MESSAGE_INITERR_RETURNSEL(EMVErrorCode.INITERR_RETURNSEL, "Application initialization return value is not equal to 9000"),
    Error_MESSAGE_INITERR_GPOCMD(EMVErrorCode.INITERR_GPOCMD, "Application initialization returns 6984"),
    Error_MESSAGE_INITERR_TLVDECODE(EMVErrorCode.INITERR_TLVDECODE, "Application initialization returns TLV parsing error"),
    Error_MESSAGE_INITERR_80VALUELEN(EMVErrorCode.INITERR_80VALUELEN, "Application initialization returns 80 template length error"),
    Error_MESSAGE_INITERR_77NOAIP(EMVErrorCode.INITERR_77NOAIP, "Application initialization returns 77 template without AIP"),
    Error_MESSAGE_INITERR_AIPLEN(EMVErrorCode.INITERR_AIPLEN, "Application initialization returns AIP length error"),
    Error_MESSAGE_INITERR_77NOAFL(EMVErrorCode.INITERR_77NOAFL, "Application initialization returns 77 template without AFL"),
    Error_MESSAGE_INITERR_AFLLEN(EMVErrorCode.INITERR_AFLLEN, "Application initialization returns AFL length error"),
    Error_MESSAGE_INITERR_UNEXPECTTAG(EMVErrorCode.INITERR_UNEXPECTTAG, "Application initialization returns invalid tag"),
    Error_MESSAGE_INITERR_NOPDOL(EMVErrorCode.INITERR_NOPDOL, "Application initialization without PDOL"),
    Error_MESSAGE_INITERR_RETURNDATA(EMVErrorCode.INITERR_RETURNDATA, "Application initialize pboc return 80 template"),
    Error_MESSAGE_INITERR_CARDNOSUPPORT(EMVErrorCode.INITERR_CARDNOSUPPORT, "Application initialization card is not supported"),
    Error_MESSAGE_INITERR_ECSELECT_QUIT(EMVErrorCode.INITERR_ECSELECT_QUIT, "Cancel electronic cash transactions"),
    Error_MESSAGE_INITERR_ECONLY_DENIAL(EMVErrorCode.INITERR_ECONLY_DENIAL, "Pure electronic cash card, but does not support e-cash"),
    Error_MESSAGE_INITERR_GPO_RETURN_6984(EMVErrorCode.INITERR_GPO_RETURN_6984, "Application initialization returns 6984< 20120911 zhengel 6984 special treatment"),
    Error_MESSAGE_INITERR_GPO_RETURN_6985(EMVErrorCode.INITERR_GPO_RETURN_6985, "Application initialization returns 6985 <20160330 fangjt 6985 directly terminate the transaction"),
    Error_MESSAGE_INITERR_GPO_RETURN_6283(EMVErrorCode.INITERR_GPO_RETURN_6283, "Application initialization returns 6283"),
    Error_MESSAGE_INITERR_GPO_RETURN_6300(EMVErrorCode.INITERR_GPO_RETURN_6300, "Application initialization returns 6300"),
    Error_MESSAGE_INITERR_GPO_RETURN_63C1(EMVErrorCode.INITERR_GPO_RETURN_63C1, "Application initialization returns 63C1"),
    Error_MESSAGE_INITERR_GPO_RETURN_6983(EMVErrorCode.INITERR_GPO_RETURN_6983, "Application initialization returns 6983"),
    Error_MESSAGE_INITERR_GPO_RETURN_6986(EMVErrorCode.INITERR_GPO_RETURN_6986, "Application initialization returns 6986"),
    Error_MESSAGE_INITERR_GPO_RETURN_9001(EMVErrorCode.INITERR_GPO_RETURN_9001, "Application initialization returns 9001"),
    Error_MESSAGE_INITERR_GPO_RETURN_6A81(EMVErrorCode.INITERR_GPO_RETURN_6A81, "Application initialization returns 6A81"),
    Error_MESSAGE_INITERR_GPO_RETURN_6A82(EMVErrorCode.INITERR_GPO_RETURN_6A82, "Application initialization returns 6A82"),
    Error_MESSAGE_INITERR_GPO_RETURN_6A83(EMVErrorCode.INITERR_GPO_RETURN_6A83, "Application initialization returns 6A83"),
    Error_MESSAGE_INITERR_GPO_RETURN_6A88(EMVErrorCode.INITERR_GPO_RETURN_6A88, "Application initialization returns 6A88"),
    Error_MESSAGE_INITERR_GPO_RETURN_6500(EMVErrorCode.INITERR_GPO_RETURN_6500, "Application initialization returns 6500"),
    Error_MESSAGE_INITERR_GPO_RETURN_6400(EMVErrorCode.INITERR_GPO_RETURN_6400, "Application initialization returns 6400"),
    Error_MESSAGE_INITERR_GPO_RETURN_9408(EMVErrorCode.INITERR_GPO_RETURN_9408, "Application initialization returns 9408"),
    Error_MESSAGE_INITERR_RF_ATC(EMVErrorCode.INITERR_RF_ATC, "Application initialization returns ATC error"),
    Error_MESSAGE_INITERR_RF_AC(EMVErrorCode.INITERR_RF_AC, "Application initialization returns AC error"),
    Error_MESSAGE_INITERR_RF_9F10(EMVErrorCode.INITERR_RF_9F10, "Application initialization returns 9F10 error"),
    Error_MESSAGE_INITERR_RF_57(EMVErrorCode.INITERR_RF_57, "Application initialization returns 57 error"),
    Error_MESSAGE_INITERR_RF_AFL(EMVErrorCode.INITERR_RF_AFL, "Application initialization returns AFL error"),
    Error_MESSAGE_INITERR_RF_5F20(EMVErrorCode.INITERR_RF_5F20, "Application initialization returns 5F20 error"),
    Error_MESSAGE_INITERR_RF_NO9F66(EMVErrorCode.INITERR_RF_NO9F66, "Application initialization without 9F66"),
    Error_MESSAGE_INITERR_RF_INSERTICC(EMVErrorCode.INITERR_RF_INSERTICC, "The insert card is detected during the contactless application initialization process"),
    Error_MESSAGE_INITERR_RF_APPNOSUPPORT(EMVErrorCode.INITERR_RF_APPNOSUPPORT, "Application initialization APP does not support"),
    Error_MESSAGE_INITERR_RF_9F27(EMVErrorCode.INITERR_RF_9F27, "Application initialization 9F27 error"),
    Error_MESSAGE_INITERR_RF_ECONLY_ONLINE(EMVErrorCode.INITERR_RF_ECONLY_ONLINE, "Pure electronic cash card but requires online"),
    Error_MESSAGE_INITERR_RF_ECONLY_CVM(EMVErrorCode.INITERR_RF_ECONLY_CVM, "Pure electronic cash card but requires CVM"),
    Error_MESSAGE_INITERR_RF_STRIPE(EMVErrorCode.EMV_ERR_READCONFIG, "Magnetic stripe card is detected during the contactless application initialization process."),
    Error_MESSAGE_INITERR_SELECT_KERNEL_ERR(EMVErrorCode.INITERR_SELECT_KERNEL_ERR, "Application initialization returns ATC error"),
    Error_MESSAGE_INITERR_GPO_SAVEDATAERR(EMVErrorCode.INITERR_GPO_SAVEDATAERR, "Application initialization failed to save data"),
    Error_MESSAGE_INITERR_77DUB_AFL(EMVErrorCode.INITERR_77DUB_AFL, "Application initialization returns 77 template AFL data duplication"),
    Error_MESSAGE_INITERR_80DUB_AFL(EMVErrorCode.EMV_ERR_READCONFIG, "Application initialization returns 80 template AFL data duplication"),
    Error_MESSAGE_INITERR_81_GET(EMVErrorCode.INITERR_81_GET, "Application initialization gets 81"),
    Error_MESSAGE_INITERR_77DUB_AIP(EMVErrorCode.INITERR_77DUB_AIP, "Application initialization returns 77 template AIP data duplication"),
    Error_MESSAGE_INITERR_80DUB_AIP(EMVErrorCode.INITERR_80DUB_AIP, "Application initialization returns 80 template AIP data duplication"),
    Error_MESSAGE_INITERR_9F01_GET(EMVErrorCode.INITERR_9F01_GET, "Application initialization returns 9F01 error"),
    Error_MESSAGE_INITERR_9F69_GET(EMVErrorCode.INITERR_9F69_GET, "Application initialization returns 9F69 error"),
    Error_MESSAGE_INITERR_SAVE_FAIL(EMVErrorCode.INITERR_SAVE_FAIL, "Application initialization failed to save data"),
    Error_MESSAGE_INITERR_PARSE_ERR(EMVErrorCode.INITERR_PARSE_ERR, "Application initialization tlv data parsing error"),
    Error_MESSAGE_INITERR_CARDDATA_MISSING(EMVErrorCode.INITERR_CARDDATA_MISSING, "Application initialization card data lose"),
    Error_MESSAGE_INITERR_AFLHEADERR(EMVErrorCode.INITERR_AFLHEADERR, "Application initialization AFL format error"),
    Error_MESSAGE_INITERR_DUPLICATED(EMVErrorCode.INITERR_DUPLICATED, "Application initialization tag repeat"),
    Error_MESSAGE_INITERR_AIP_MISSING(EMVErrorCode.INITERR_AIP_MISSING, "JCB application initialization without return AIP"),
    Error_MESSAGE_INITERR_SFI_MISSING(EMVErrorCode.INITERR_SFI_MISSING, "JCB application initialization without return SFI"),
    Error_MESSAGE_INITERR_ILLEGALTAG(EMVErrorCode.INITERR_ILLEGALTAG, "JCB application initialization is not 77 or 80 template"),
    Error_MESSAGE_INITERR_INVALID_SFI(EMVErrorCode.INITERR_INVALID_SFI, "JCB application initializes SFI error"),
    Error_MESSAGE_INITERR_QUIT(EMVErrorCode.INITERR_QUIT, "Application initialization cancel transaction"),
    Error_MESSAGE_INITERR_FFI_NOSUPP_CONTAACTLESS(EMVErrorCode.INITERR_FFI_NOSUPP_CONTAACTLESS, "Interac FFI does not support contactless"),
    Error_MESSAGE_INITERR_FFI_NOSUPP_MOBILE(EMVErrorCode.INITERR_FFI_NOSUPP_MOBILE, "Interac FFI does not support mobile phones"),
    Error_MESSAGE_INITERR_FFI_WRONG(EMVErrorCode.INITERR_FFI_WRONG, "Interac FFI value error"),
    Error_MESSAGE_INITERR_NO_CTI(EMVErrorCode.INITERR_NO_CTI, "interac no CTI"),
    Error_MESSAGE_INITERR_CTI_LENTHWRONG(EMVErrorCode.INITERR_CTI_LENTHWRONG, "interac CTI lenth wrong"),
    Error_MESSAGE_INITERR_CTI_TRYOTHERINTERFACE(EMVErrorCode.INITERR_CTI_TRYOTHERINTERFACE, "Interac CTI requires a transfer interface"),
    Error_MESSAGE_INITERR_CTI_OTHERTERMINAL(EMVErrorCode.INITERR_CTI_OTHERTERMINAL, "Interac CTI requires a transfer interface, but this machine does not support,viewing other machines"),
    Error_MESSAGE_INITERR_CTI_NOOTHERTERMINAL(EMVErrorCode.INITERR_CTI_NOOTHERTERMINAL, "Interac CTI requires a transfer interface, which is not supported by this machine and other machines."),
    Error_MESSAGE_INITERR_OVER_RETRYLIMIT(EMVErrorCode.INITERR_OVER_RETRYLIMIT, "Interac exceeds the maximum number of try again"),
    Error_MESSAGE_INITERR_SECONDTAPWRONG(EMVErrorCode.INITERR_SECONDTAPWRONG, "Rupay second Remove the card and put it back later is mismatch"),
    Error_MESSAGE_INITERR_GPO_RESPONSE_ERR(EMVErrorCode.INITERR_GPO_RESPONSE_ERR, "GPO APDU response exception"),
    Error_MESSAGE_INITERR_GPO_RETURN_6D00(EMVErrorCode.INITERR_GPO_RETURN_6D00, "Application initialization returns 6D00"),
    Error_MESSAGE_INITERR_GPO_RETURN_6588(EMVErrorCode.INITERR_GPO_RETURN_6588, "Application initialization returns 6588"),
    Error_MESSAGE_INITERR_AIP_NOSUPPCDA(EMVErrorCode.INITERR_AIP_NOSUPPCDA, "Application initialization returns AIP NO Support CDA"),
    Error_MESSAGE_INITERR_9F02_WRONG(EMVErrorCode.INITERR_9F02_WRONG, "CPACE Amount, Authorized is missing or Amount, Authorized is empty (Length = 0)"),
    Error_MESSAGE_INITERR_5F2A_WRONG(EMVErrorCode.INITERR_5F2A_WRONG, "CPACE Transaction Currency Code is missing or Transaction Currency Code is empty (Length = 0)"),
    Error_MESSAGE_INiTERR_AIP_CDCVMLIMIT(EMVErrorCode.INITERR_AIP_CDCVMLIMIT, "CPACE Amount, Authorized > Contactless Transaction Limit"),
    Error_MESSAGE_INITERR_AIP_NOSUPPEMV(EMVErrorCode.INITERR_AIP_NOSUPPEMV, "Application initialization returns AIP NO Support CDA"),
    Error_MESSAGE_INITERR_5F34DUP(EMVErrorCode.INITERR_5F34DUP, "5F34 Repeat"),
    Error_MESSAGE_INITERR_9F26DUP(EMVErrorCode.INITERR_9F26DUP, "9F26 Repeat"),


    Error_MESSAGE_READRECERR_BASE(EMVErrorCode.READRECERR_BASE, "Read record benchmark error code"),
    Error_MESSAGE_READREC_SFIERR(EMVErrorCode.READREC_SFIERR, "Read record SFI error"),
    Error_MESSAGE_READREC_FIRSTBE0(EMVErrorCode.READREC_FIRSTBE0, "Read record first record error"),
    Error_MESSAGE_READREC_RECRANGEERR(EMVErrorCode.READREC_RECRANGEERR, "Read record SFI record range error"),
    Error_MESSAGE_READREC_CMDERR(EMVErrorCode.READREC_CMDERR, "Read record return code error"),
    Error_MESSAGE_READREC_TLVERR(EMVErrorCode.READREC_TLVERR, "Read record TLV parsing error"),
    Error_MESSAGE_READREC_NO5A(EMVErrorCode.READREC_NO5A, "Read record without return tag 5A"),
    Error_MESSAGE_READREC_NO8C(EMVErrorCode.READREC_NO8C, "Read record without return tag 8C"),
    Error_MESSAGE_READREC_NO8D(EMVErrorCode.READREC_NO8D, "Read record without return tag 8D"),
    Error_MESSAGE_READREC_5F24ERR(EMVErrorCode.READREC_5F24ERR, "Read record tag5F24 error"),
    Error_MESSAGE_READREC_5F25ERR(EMVErrorCode.READREC_5F25ERR, "Read record tag5F25 error"),
    Error_MESSAGE_READREC_SAVEDATA(EMVErrorCode.READREC_SAVEDATA, "Failed to read record storage data"),
    Error_MESSAGE_READREC_RET_TEMDATA(EMVErrorCode.READREC_RET_TEMDATA, "readrecord return Terminal Data,so terminate"),
    Error_MESSAGE_READREC_LASTCMDERR(EMVErrorCode.READREC_LASTCMDERR, "The last readrecord cmd failed (this macro value is immutable"),
    Error_MESSAGE_READREC_NO57(EMVErrorCode.READREC_NO57, "Read record without return tag 57"),
    Error_MESSAGE_READREC_NO5F20(EMVErrorCode.READREC_NO5F20, "Read record without return tag 5F20"),
    Error_MESSAGE_READREC_NO9F74(EMVErrorCode.READREC_NO9F74, "Read record without return tag 9F74"),
    Error_MESSAGE_READREC_NO9F79(EMVErrorCode.READREC_NO9F79, "Read record without return tag 9F79"),
    Error_MESSAGE_READREC_NO9F36(EMVErrorCode.READREC_NO9F36, "Read record without return tag 9F36"),
    Error_MESSAGE_READREC_ERR_ATC(EMVErrorCode.READREC_ERR_ATC, "Read record returns tag 9F36 error"),
    Error_MESSAGE_READREC_ERR_DATEEXPIRE(EMVErrorCode.READREC_ERR_DATEEXPIRE, "Transaction date expired"),
    Error_MESSAGE_READREC_ERR_DATENOEFFECT(EMVErrorCode.READREC_ERR_DATENOEFFECT, "The date of transaction is not valid"),
    Error_MESSAGE_READREC_RETURN_6283(EMVErrorCode.READREC_RETURN_6283, "Read record returns to 6283"),
    Error_MESSAGE_READREC_RETURN_6300(EMVErrorCode.READREC_RETURN_6300, "Read record returns to 6300"),
    Error_MESSAGE_READREC_RETURN_63C1(EMVErrorCode.READREC_RETURN_63C1, "Read record returns to 63C1"),
    Error_MESSAGE_READREC_RETURN_6983(EMVErrorCode.READREC_RETURN_6983, "Read record returns to 6983"),
    Error_MESSAGE_READREC_RETURN_6984(EMVErrorCode.READREC_RETURN_6984, "Read record returns to 6984"),
    Error_MESSAGE_READREC_RETURN_6985(EMVErrorCode.READREC_RETURN_6985, "Read record returns to 6985"),
    Error_MESSAGE_READREC_RETURN_6A81(EMVErrorCode.READREC_RETURN_6A81, "Read record returns to 6A81"),
    Error_MESSAGE_READREC_RETURN_6A82(EMVErrorCode.READREC_RETURN_6A82, "Read record returns to 6A82"),
    Error_MESSAGE_READREC_RETURN_6A83(EMVErrorCode.READREC_RETURN_6A83, "Read record returns to 6A83"),
    Error_MESSAGE_READREC_RETURN_6A88(EMVErrorCode.READREC_RETURN_6A88, "Read record returns to 6A88"),
    Error_MESSAGE_READREC_RETURN_6400(EMVErrorCode.READREC_RETURN_6400, "Read record returns to 6400"),
    Error_MESSAGE_READREC_RETURN_6500(EMVErrorCode.READREC_RETURN_6500, "Read record returns to 6500"),
    Error_MESSAGE_READREC_RETURN_9001(EMVErrorCode.READREC_RETURN_9001, "Read record returns to 9001"),
    Error_MESSAGE_READREC_RETURN_5ADUP(EMVErrorCode.READREC_RETURN_5ADUP, "Read record returns 5A repeat"),
    Error_MESSAGE_READREC_RETURN_5F24DUP(EMVErrorCode.READREC_RETURN_5F24DUP, "Read record returns 5F24 repeat"),
    Error_MESSAGE_READREC_RETURN_57DUP(EMVErrorCode.READREC_RETURN_57DUP, "Read record returns 57 repeat"),
    Error_MESSAGE_READREC_QUIT(EMVErrorCode.READREC_QUIT, "Read record cancel transaction"),
    Error_MESSAGE_READREC_DATEWRONG(EMVErrorCode.READREC_DATEWRONG, "The date of the card returned by the read record is incorrect"),
    Error_MESSAGE_READREC_NOSAME5A57(EMVErrorCode.READREC_NOSAME5A57, "5A and 57 returned by the read record do not match"),
    Error_MESSAGE_READREC_NO9F08(EMVErrorCode.READREC_NO9F08, "Read record without return tag 9F08"),
    Error_MESSAGE_READREC_NO9F02(EMVErrorCode.READREC_NO9F02, "Read record without return tag 9F02"),
    Error_MESSAGE_READREC_MAX_LIMIT_EXCEEDED(EMVErrorCode.READREC_MAX_LIMIT_EXCEEDED, "Read records exceed the maximum limit"),
    Error_MESSAGE_READREC_ERR_PP_ERR_9F4A(EMVErrorCode.READREC_ERR_PP_ERR_9F4A, "Read record returns tag 9F4A error"),
    Error_MESSAGE_READREC_ERR_PP_NO9F4A(EMVErrorCode.READREC_ERR_PP_NO9F4A, "Read record without return tag 9F4A"),
    Error_MESSAGE_READREC_ERR_PP_NO8F(EMVErrorCode.READREC_ERR_PP_NO8F, "Read record without return tag 8F"),
    Error_MESSAGE_READREC_ERR_PP_NO90(EMVErrorCode.READREC_ERR_PP_NO90, "Read record without return tag 90"),
    Error_MESSAGE_READREC_ERR_PP_NO9F32(EMVErrorCode.READREC_ERR_PP_NO9F32, "Read record without return tag 9F32"),
    Error_MESSAGE_READREC_ERR_PP_NO93(EMVErrorCode.READREC_ERR_PP_NO93, "Read record without return tag 93"),
    Error_MESSAGE_READREC_ERR_PP_NO9F46(EMVErrorCode.READREC_ERR_PP_NO9F46, "Read record without return tag 9F46"),
    Error_MESSAGE_READREC_ERR_PP_NO9F47(EMVErrorCode.READREC_ERR_PP_NO9F47, "Read record without return tag 9F47"),
    Error_MESSAGE_READREC_ERR_PP_CAPKNOSURPT(EMVErrorCode.READREC_ERR_PP_CAPKNOSURPT, "Capk does not support"),
    Error_MESSAGE_READREC_ERR_PP_CARDDATA(EMVErrorCode.READREC_ERR_PP_CARDDATA, "ICC return CardReader Data,so terminate"),
    Error_MESSAGE_READREC_ERR_PW_NO57(EMVErrorCode.READREC_ERR_PW_NO57, "Read record without return tag 57"),
    Error_MESSAGE_READREC_FMT_ERROR(EMVErrorCode.READREC_FMT_ERROR, "Read record return data format error"),
    Error_MESSAGE_READREC_NO5F24(EMVErrorCode.READREC_NO5F24, "Read record without return tag 5F24"),
    Error_MESSAGE_READREC_TAG9F42_INVALID(EMVErrorCode.READREC_TAG9F42_INVALID, "Read record TAG 9F42 INVALID"),
    Error_MESSAGE_READREC_TAG5F25_INVALID(EMVErrorCode.READREC_TAG5F25_INVALID, "Read record TAG 5F25 INVALID"),
    Error_MESSAGE_READREC_TAG5A_INVALID(EMVErrorCode.READREC_TAG5A_INVALID, "Read record TAG 5A INVALID"),
    Error_MESSAGE_READREC_TAG9F07_INVALID(EMVErrorCode.READREC_TAG9F07_INVALID, "Read record TAG 9F07 INVALID"),
    Error_MESSAGE_READREC_TAG5F20_INVALID(EMVErrorCode.READREC_TAG5F20_INVALID, "Read record TAG 5F20 INVALID"),
    Error_MESSAGE_READREC_TAG9F0D_INVALID(EMVErrorCode.READREC_TAG9F0D_INVALID, "Read record TAG 9F0D INVALID"),
    Error_MESSAGE_READREC_TAG9F0E_INVALID(EMVErrorCode.READREC_TAG9F0E_INVALID, "Read record TAG 9F0E INVALID"),
    Error_MESSAGE_READREC_TAG9F0F_INVALID(EMVErrorCode.READREC_TAG9F0F_INVALID, "Read record TAG 9F0F INVALID"),
    Error_MESSAGE_READREC_TAG5F34_INVALID(EMVErrorCode.READREC_TAG5F34_INVALID, "Read record TAG 5F34 INVALID"),
    Error_MESSAGE_READREC_TAG9F11_INVALID(EMVErrorCode.READREC_TAG9F11_INVALID, "Read record TAG 9F11 INVALID"),
    Error_MESSAGE_READREC_TAG5F28_INVALID(EMVErrorCode.READREC_TAG5F28_INVALID, "Read record TAG 5F28 INVALID"),
    Error_MESSAGE_READREC_TAG8F_INVALID(EMVErrorCode.READREC_TAG8F_INVALID, "Read record TAG 8F INVALID"),
    Error_MESSAGE_READREC_NO9F6D(EMVErrorCode.READREC_NO9F6D, "Read record without return tag 9F6D"),
    Error_MESSAGE_READREC_NO5F28(EMVErrorCode.READREC_NO5F28, "Read record without return tag 5F28"),
    Error_MESSAGE_READREC_NO9F07(EMVErrorCode.READREC_NO9F07, "Read record without return tag 9F07"),


    Error_MESSAGE_SECERR_BASE(EMVErrorCode.SECERR_BASE, "Data authentication benchmark error code"),
    Error_MESSAGE_SECERR_ICCDATAMISSING(EMVErrorCode.SECERR_ICCDATAMISSING, "Ic card data loss"),
    Error_MESSAGE_SECERR_CERTLENGTH(EMVErrorCode.SECERR_CERTLENGTH, "Data Authentication Certificate Length Error"),
    Error_MESSAGE_SECERR_RECOVERKEY(EMVErrorCode.SECERR_RECOVERKEY, "Data authentication RSA failed to recover public key"),
    Error_MESSAGE_SECERR_DATAHEADER(EMVErrorCode.SECERR_DATAHEADER, "Data authentication recovery data header error"),
    Error_MESSAGE_SECERR_FORMATWRONG(EMVErrorCode.SECERR_FORMATWRONG, "The second byte of the data authentication certificate is wrong"),
    Error_MESSAGE_SECERR_DATATAILER(EMVErrorCode.SECERR_DATATAILER, "Second to last byte of the data authentication certificate is wrong"),
    Error_MESSAGE_SECERR_RECOVERHASH(EMVErrorCode.SECERR_RECOVERHASH, "Data authentication hash value check does not match"),
    Error_MESSAGE_SECERR_ALGORITHM(EMVErrorCode.SECERR_ALGORITHM, "Data authentication algorithm identification error"),
    Error_MESSAGE_SECERR_MODULUSLENGTH(EMVErrorCode.SECERR_MODULUSLENGTH, "Data Authentication Certificate Module Length error"),
    Error_MESSAGE_SECERR_CERTEXPIRED(EMVErrorCode.SECERR_CERTEXPIRED, "Data Authentication Certificate expires"),
    Error_MESSAGE_SECERR_CERTREVOC(EMVErrorCode.SECERR_CERTREVOC, "Data authentication and certification center public key blacklist"),
    Error_MESSAGE_SECERR_SSADLEN(EMVErrorCode.SECERR_SSADLEN, "Data authentication SSAD length error"),
    Error_MESSAGE_SECERR_RECOVERSSAD(EMVErrorCode.SECERR_RECOVERSSAD, "Data authentication recovery SSAD error"),
    Error_MESSAGE_SECERR_9F4AERR(EMVErrorCode.SECERR_9F4AERR, "Data authentication 9F4A error"),
    Error_MESSAGE_SECERR_NONEDDOL(EMVErrorCode.SECERR_NONEDDOL, "Data authentication without default DDOL"),
    Error_MESSAGE_SECERR_NO9F37(EMVErrorCode.SECERR_NO9F37, "Data authentication without tag 9F37"),
    Error_MESSAGE_SECERR_DDOLPROCESS(EMVErrorCode.SECERR_DDOLPROCESS, "Data authentication DDOL package error"),
    Error_MESSAGE_SECERR_SDADLEN(EMVErrorCode.SECERR_SDADLEN, "Data authentication SDAD length error"),
    Error_MESSAGE_SECERR_NOISSUERPK(EMVErrorCode.SECERR_NOISSUERPK, "Data authentication without issuing bank public key"),
    Error_MESSAGE_SECERR_NOICCPK(EMVErrorCode.SECERR_NOICCPK, "Data authentication without IC card public key"),
    Error_MESSAGE_SECERR_GETCHALLENGE(EMVErrorCode.SECERR_GETCHALLENGE, "Data Authentication Acquisition Random Number error"),
    Error_MESSAGE_SECERR_RECOVERENCPIN(EMVErrorCode.SECERR_RECOVERENCPIN, "Data Authentication Recovery RSA Data error"),
    Error_MESSAGE_SECERR_NO9F4B(EMVErrorCode.SECERR_NO9F4B, "Data authentication without tag 9F4B"),
    Error_MESSAGE_SECERR_RECOVERSDAD(EMVErrorCode.SECERR_RECOVERSDAD, "Data Authentication Recovery SDAD Error"),
    Error_MESSAGE_SECERR_SCDADLEN(EMVErrorCode.SECERR_SCDADLEN, "Data Authentication Recovery SCDAD Error"),
    Error_MESSAGE_SECERR_CIDNOTMATCHED(EMVErrorCode.SECERR_CIDNOTMATCHED, "Data Authentication CID Value Mismatch"),
    Error_MESSAGE_SECERR_CDAHASH1(EMVErrorCode.SECERR_CDAHASH1, "Data authentication hash check 1 error"),
    Error_MESSAGE_SECERR_CDAHASH2(EMVErrorCode.SECERR_CDAHASH2, "Data authentication hash check 2 error"),
    Error_MESSAGE_SECERR_FAILINREADREC(EMVErrorCode.SECERR_FAILINREADREC, "Data Authentication Reading Record Error"),
    Error_MESSAGE_SECERR_PANNOTMATCH(EMVErrorCode.SECERR_PANNOTMATCH, "Data Authentication Card Number Mismatch"),
    Error_MESSAGE_SECERR_CAPKNOTFOUND(EMVErrorCode.SECERR_CAPKNOTFOUND, "Data Authentication and Authentication Center Public Key Mismatch"),
    Error_MESSAGE_SECERR_NO9F36(EMVErrorCode.SECERR_NO9F36, "Data authentication without tag 9F36"),
    Error_MESSAGE_SECERR_FDDAVERNOTSUP(EMVErrorCode.SECERR_FDDAVERNOTSUP, "Data Authentication FDDA Version does not support"),
    Error_MESSAGE_SECERR_FDDA9F69LENERR(EMVErrorCode.SECERR_FDDA9F69LENERR, "Data Authentication FDDA 9F69 Length Error"),
    Error_MESSAGE_SECERR_ALGORITHMPARAM(EMVErrorCode.SECERR_ALGORITHMPARAM, "Data Authentication national secret Elliptic Parameter Identification Error"),
    Error_MESSAGE_SECERR_SM2VERIFY(EMVErrorCode.SECERR_SM2VERIFY, "Data authentication SM2 authentication signature error"),
    Error_MESSAGE_SECERR_9F69(EMVErrorCode.SECERR_9F69, "Data authentication 9F69 error"),
    Error_MESSAGE_SECERR_FDDA_VER(EMVErrorCode.SECERR_FDDA_VER, "Data authentication FDDA version error"),
    Error_MESSAGE_SECERR_ATC(EMVErrorCode.SECERR_ATC, "Data authentication ATC error"),
    Error_MESSAGE_SECERR_INALCMD_ERRDATA(EMVErrorCode.SECERR_INALCMD_ERRDATA, "Data authentication forces data errors"),
    Error_MESSAGE_SECERR_NOPAN(EMVErrorCode.SECERR_NOPAN, "ata authentication without tag 5A"),
    Error_MESSAGE_SECERR_ICCDDLEN(EMVErrorCode.SECERR_ICCDDLEN, "he length of ICC Dynamic Data is less"),
    Error_MESSAGE_SECERR_RRP(EMVErrorCode.SECERR_RRP, "paypass CDA RRP not match"),
    Error_MESSAGE_SECERR_ERRHASH_INDICATOR(EMVErrorCode.SECERR_ERRHASH_INDICATOR, "Hash indication of data authentication error"),
    Error_MESSAGE_SECERR_NOHASH_ALGORITHM(EMVErrorCode.SECERR_NOHASH_ALGORITHM, "Data authentication without hash algorithm"),
    Error_MESSAGE_SECERR_NO9F4BOR92(EMVErrorCode.SECERR_NO9F4BOR92, "Data authentication without return tag9F4B or tag92"),
    Error_MESSAGE_SECERR_FAILDDA(EMVErrorCode.SECERR_FAILDDA, "Data authentication DDA failed"),
    Error_MESSAGE_SECERR_NOREMAINDER(EMVErrorCode.SECERR_NOREMAINDER, "Without 92 or 9F48"),
    Error_MESSAGE_SECERR_NOCARDID(EMVErrorCode.SECERR_NOCARDID, "DPAS Without Card ID"),
    Error_MESSAGE_SECERR_NOMATCHCARDID(EMVErrorCode.SECERR_NOMATCHCARDID, "DPAS no match Card ID"),
    Error_MESSAGE_SECERR_CDAHASH3(EMVErrorCode.SECERR_CDAHASH3, "DPAS Data authentication hash check 3 error"),
    Error_MESSAGE_SECERR_9F4CERROR(EMVErrorCode.SECERR_9F4CERROR, "SECERR_9F4CERROR"),
    Error_MESSAGE_SECERR_ECC_FORMAT(EMVErrorCode.SECERR_ECC_FORMAT, "ECC cert format wrong"),
    Error_MESSAGE_SECERR_ECC_ENCODING(EMVErrorCode.SECERR_ECC_ENCODING, "ECC cert Encoding wrong"),
    Error_MESSAGE_SECERR_ECC_RID(EMVErrorCode.SECERR_ECC_RID, "ECC cert RID wrong"),
    Error_MESSAGE_SECERR_ECC_INDEX(EMVErrorCode.SECERR_ECC_INDEX, "ECC cert Index wrong"),
    Error_MESSAGE_SECERR_ECC_VERIFY(EMVErrorCode.SECERR_ECC_VERIFY, "Data authentication ECC authentication signature error"),
    Error_MESSAGE_SECERR_ECC_HASHALG(EMVErrorCode.SECERR_ECC_HASHALG, "Data authentication ECC Hash error"),
    Error_MESSAGE_SECERR_ECC_ICCHASHWRONG(EMVErrorCode.SECERR_ECC_ICCHASHWRONG, "Data authentication ICC ECC Hash check error"),


    Error_MESSAGE_CVERR_BASE(EMVErrorCode.CVERR_BASE, "Cardholder Certification benchmark Error Code"),
    Error_MESSAGE_CVERR_8ELENWRONG(EMVErrorCode.CVERR_8ELENWRONG, "tag8E length error"),
    Error_MESSAGE_CVERR_OFFLINEPIN(EMVErrorCode.CVERR_OFFLINEPIN, "Input offline pin failed"),
    Error_MESSAGE_CVERR_ONLINEPIN(EMVErrorCode.CVERR_ONLINEPIN, "Input online pin failed"),
    Error_MESSAGE_CVERR_AIPCVM_NOSUPP(EMVErrorCode.CVERR_AIPCVM_NOSUPP, "Card AIP does not support CVM"),
    Error_MESSAGE_CVERR_NO8E(EMVErrorCode.CVERR_NO8E, "Without CVM list"),
    Error_MESSAGE_CVERR_NOCVMRULES(EMVErrorCode.CVERR_NOCVMRULES, "Without CVM rules"),
    Error_MESSAGE_CVERR_DPASCDCVMNOENROLLED(EMVErrorCode.CVERR_DPASCDCVMNOENROLLED, "DPAS CDCVM Not Enrolled"),
    Error_MESSAGE_CVERR_DPASCDCVMNOTPERFORMED(EMVErrorCode.CVERR_DPASCDCVMNOTPERFORMED, "DPAS CDCVM Not Performed"),


    Error_MESSAGE_GACERR_BASE(EMVErrorCode.GACERR_BASE, "Terminal and card behavior analysis benchmark error code"),
    Error_MESSAGE_GACERR_WRONGREQ(EMVErrorCode.GACERR_WRONGREQ, "GAC response error"),
    Error_MESSAGE_GACERR_CDOLPACKET(EMVErrorCode.GACERR_CDOLPACKET, "GAC CDOL data pack error"),
    Error_MESSAGE_GACERR_GACCMD(EMVErrorCode.GACERR_GACCMD, "GAC return code error"),
    Error_MESSAGE_GACERR_TLVDEOCDE(EMVErrorCode.GACERR_TLVDEOCDE, "GAC returns data parsing error"),
    Error_MESSAGE_GACERR_CDAREQUIRE77(EMVErrorCode.GACERR_CDAREQUIRE77, "Tag 80 templet cda requested and AAC not returned"),
    Error_MESSAGE_GACERR_TAG80VALLEN(EMVErrorCode.GACERR_TAG80VALLEN, "GAC Returns Tag Length Error"),
    Error_MESSAGE_GACERR_77NO9F27(EMVErrorCode.GACERR_77NO9F27, "GAC returns 77 templates without returning 9F27"),
    Error_MESSAGE_GACERR_77NO9F36(EMVErrorCode.GACERR_77NO9F36, "GAC returns 77 templates without returning 9F36"),
    Error_MESSAGE_GACERR_77NO9F4B(EMVErrorCode.GACERR_77NO9F4B, "GAC returns 77 templates without returning 9F4B"),
    Error_MESSAGE_GACERR_NOT77OR80(EMVErrorCode.GACERR_NOT77OR80, "GAC returns not 77 or 80 templates"),
    Error_MESSAGE_GACERR_AARRET(EMVErrorCode.GACERR_AARRET, "CID request AAR returned by GAC"),
    Error_MESSAGE_GACERR_WRONGCID(EMVErrorCode.GACERR_WRONGCID, "GAC returns the wrong CID"),
    Error_MESSAGE_GACERR_77NO9F26(EMVErrorCode.GACERR_77NO9F26, "GAC returns 77 templates without returning 9F26"),
    Error_MESSAGE_GACERR_NO9F10(EMVErrorCode.GACERR_NO9F10, "GAC without return 9F10"),
    Error_MESSAGE_GACERR_SPECIAL_PAD0(EMVErrorCode.GACERR_SPECIAL_PAD0, "GAC returns zero data"),
    Error_MESSAGE_GACERR_DRDOLPACKET(EMVErrorCode.GACERR_DRDOLPACKET, "DRDOL Data Pack Failed"),
    Error_MESSAGE_GACERR_RAC_SW12_NO9000(EMVErrorCode.GACERR_RAC_SW12_NO9000, "RAC response code is not 9000"),
    Error_MESSAGE_GACERR_80_9F36_EXIST(EMVErrorCode.GACERR_80_9F36_EXIST, "GAC returns 80 templates with 9F36"),
    Error_MESSAGE_GACERR_ECMAC(EMVErrorCode.GACERR_ECMAC, "GAC Error in Electronic Cash"),
    Error_MESSAGE_GACERR_GETECBALANCE(EMVErrorCode.GACERR_GETECBALANCE, "Failed to obtain EC balance"),
    Error_MESSAGE_GACERR_EC_BALANCELACK(EMVErrorCode.GACERR_EC_BALANCELACK, "EC Balance not enough"),
    Error_MESSAGE_GACERR_ECONLY_GOONLINE(EMVErrorCode.GACERR_ECONLY_GOONLINE, "Pure electronic cash card requires EC online but refuse"),
    Error_MESSAGE_GACERR_EC_THRESHOLD(EMVErrorCode.GACERR_EC_THRESHOLD, "EC balance < transaction amount + threshold, resulting in online"),
    Error_MESSAGE_GACERR_RETURN_81(EMVErrorCode.GACERR_RETURN_81, "GAC returns 77 templates without returning 81"),
    Error_MESSAGE_GACERR_RETURN_9F01(EMVErrorCode.GACERR_RETURN_9F01, "GAC returns 77 templates without returning 9F01"),
    Error_MESSAGE_GACERR_RETURN_ERROR(EMVErrorCode.GACERR_RETURN_ERROR, "GAC returns CID length error"),
    Error_MESSAGE_GACERR_9F10ERROR(EMVErrorCode.GACERR_9F10ERROR, "GAC returns 9F10 format error"),
    Error_MESSAGE_GACERR_77_GACNOC5(EMVErrorCode.GACERR_77_GACNOC5, "GAC returns 77 templates without returning tag C5"),
    Error_MESSAGE_GACERR_77_ALLNOC5(EMVErrorCode.GACERR_77_ALLNOC5, "Neither MCCS GPO nor GAC returned to tag C5"),
    Error_MESSAGE_GACERR_DISTINCTCVMINFOR(EMVErrorCode.GACERR_DISTINCTCVMINFOR, "MCCS GPO and GAC return tage C5 CVM different ways"),
    Error_MESSAGE_GACERR_ECHO(EMVErrorCode.GACERR_ECHO, "MCCS GAC apdu without return, need to enter torn transaction"),
    Error_MESSAGE_GACERR_77NO9F4BHAVE9F26(EMVErrorCode.GACERR_77NO9F4BHAVE9F26, "MCCS GAC without 9F4B but has 9F26"),
    Error_MESSAGE_GACERR_CDOL1_PACK(EMVErrorCode.GACERR_CDOL1_PACK, "First GAC CDOL package failed"),
    Error_MESSAGE_GACERR_FMT_ERROR(EMVErrorCode.GACERR_FMT_ERROR, "The 77 template format returned by JCB GAC is wrong."),
    Error_MESSAGE_GACERR_TAG_DUP(EMVErrorCode.GACERR_TAG_DUP, "JCB failed to store the label returned by GAC"),
    Error_MESSAGE_GACERR_CID_MISSING(EMVErrorCode.GACERR_CID_MISSING, "JCB storage GAC without return CID"),
    Error_MESSAGE_GACERR_ATC_MISSING(EMVErrorCode.GACERR_ATC_MISSING, "JCB GAC without return ATC"),
    Error_MESSAGE_GACERR_9F4B_MISSING(EMVErrorCode.GACERR_9F4B_MISSING, "JCB GAC without return 9F4B"),
    Error_MESSAGE_GACERR_AC_MISSING(EMVErrorCode.GACERR_AC_MISSING, "JCB GAC without return AC"),
    Error_MESSAGE_GACERR_9F50_MISSING(EMVErrorCode.GACERR_9F50_MISSING, "JCB GAC without return 9F50"),
    Error_MESSAGE_GACERR_ACTYPE_ERR(EMVErrorCode.GACERR_ACTYPE_ERR, "JCB GAC return AC type wrong"),
    Error_MESSAGE_GACERR_AAC(EMVErrorCode.GACERR_AAC, "JCB GAC return AAC"),
    Error_MESSAGE_GACERR_9F5F_INVALID(EMVErrorCode.GACERR_9F5F_INVALID, "JCB GAC returns 9F5F format error"),
    Error_MESSAGE_GACERR_9F60_INVALID(EMVErrorCode.GACERR_9F60_INVALID, "JCB GAC returns 9F60 format error"),
    Error_MESSAGE_CVM_NOT_SUPPORT(EMVErrorCode.CVM_NOT_SUPPORT, "JCB does not support CVM authentication"),
    Error_MESSAGE_GACERR_LEGACY_FMT(EMVErrorCode.GACERR_LEGACY_FMT, "JCB LEGACY mode GAC returns not 80 template"),
    Error_MESSAGE_GACERR_LEGACY_DENIAL(EMVErrorCode.GACERR_LEGACY_DENIAL, "JCB LEGACY mode GAC returned CID is not ARQC"),
    Error_MESSAGE_GACERR_QUIT(EMVErrorCode.GACERR_QUIT, "GAC cancels the transaction"),
    Error_MESSAGE_GACERR_9F27LENWRONG(EMVErrorCode.GACERR_9F27LENWRONG, "9F27 length error"),
    Error_MESSAGE_GACERR_9F36LENWRONG(EMVErrorCode.GACERR_9F36LENWRONG, "9F36 length error"),
    Error_MESSAGE_GACERR_9F26LENWRONG(EMVErrorCode.GACERR_9F26LENWRONG, "9F26 length error"),
    Error_MESSAGE_GMDERR_BASE(EMVErrorCode.GMDERR_BASE, "JCB GMD command benchmark Error Code"),
    Error_MESSAGE_GMDERR_MDOL_PACK(EMVErrorCode.GMDERR_MDOL_PACK, "JCB GMD failed to package MDOL"),
    Error_MESSAGE_GMDERR_FMT_ERROR(EMVErrorCode.GMDERR_FMT_ERROR, "JCB GMD command returns data error"),
    Error_MESSAGE_GMDERR_TK2ED_MISSING(EMVErrorCode.GMDERR_TK2ED_MISSING, "JCB GMD command without return tag57"),
    Error_MESSAGE_GMDERR_MS_DENIAL(EMVErrorCode.GMDERR_MS_DENIAL, "JCB MS mode GMD return code is 6300"),


    Error_MESSAGE_EHCO_BASE(EMVErrorCode.EHCO_BASE, "echo command benchmark Error Code"),
    Error_MESSAGE_EHCO_FMT_ERROR(EMVErrorCode.EHCO_FMT_ERROR, "JCB echo command returns data format error"),
    Error_MESSAGE_EHCO_TAG_DUP(EMVErrorCode.EHCO_TAG_DUP, "JCB echo returns data with duplicate tag"),
    Error_MESSAGE_EHCO_CID_MISSING(EMVErrorCode.EHCO_CID_MISSING, "JCB echo without return CID"),
    Error_MESSAGE_EHCO_ATC_MISSING(EMVErrorCode.EHCO_ATC_MISSING, "JCB echo without return ATC"),
    Error_MESSAGE_EHCO_9F4B_MISSING(EMVErrorCode.EHCO_9F4B_MISSING, "JCB echo without return 9F4B"),
    Error_MESSAGE_EHCO_AC_MISSING(EMVErrorCode.EHCO_AC_MISSING, "JCB echo without return AC"),
    Error_MESSAGE_EHCO_9F50_MISSING(EMVErrorCode.EHCO_9F50_MISSING, "JCB echo without return 9F50"),
    Error_MESSAGE_EHCO_QUIT(EMVErrorCode.EHCO_QUIT, "Echo command cancel transaction"),


    Error_MESSAGE_COMERR_BASE(EMVErrorCode.COMERR_BASE, "Basic and EMV complete benchmark error code"),
    Error_MESSAGE_COMERR_BASE_SCRIPT(EMVErrorCode.COMERR_BASE_SCRIPT, "Script exceeds limit"),
    Error_MESSAGE_COMERR_BASE_SCRIPTEMPTY(EMVErrorCode.COMERR_BASE_SCRIPTEMPTY, "EC script empty"),
    Error_MESSAGE_COMERR_BASE_ECLOADAMOUNT(EMVErrorCode.COMERR_BASE_ECLOADAMOUNT, "EC deposit amount exceeds the limit"),
    Error_MESSAGE_COMERR_BASE_SCRIPTRET(EMVErrorCode.COMERR_BASE_SCRIPTRET, "Script execution error"),
    Error_MESSAGE_COMERR_BASE_SCRIPTERROR(EMVErrorCode.COMERR_BASE_SCRIPTERROR, "Script error"),


    Error_MESSAGE_FLASHCARD_ERR_BASE(EMVErrorCode.FLASHCARD_ERR_BASE, "Qpboc flash card benchmark error code"),
    Error_MESSAGE_FLASHCARD_ERR_PAN_NO_EQUAL(EMVErrorCode.FLASHCARD_ERR_PAN_NO_EQUAL, "Flash card number does not match"),
    Error_MESSAGE_FLASHCARD_ERR_ATC_NO_EQUAL(EMVErrorCode.FLASHCARD_ERR_ATC_NO_EQUAL, "Flash card application transaction counter does not match"),
    Error_MESSAGE_FLASHCARD_ERR_CURCODE_NO_EQUAL(EMVErrorCode.FLASHCARD_ERR_CURCODE_NO_EQUAL, "Flash card currency code does not match"),
    Error_MESSAGE_FLASHCARD_ERR_BALANCE_NO_EQUAL(EMVErrorCode.FLASHCARD_ERR_BALANCE_NO_EQUAL, "Flash card electronic cash balance does not match"),
    Error_MESSAGE_FLASHCARD_ERR_NO_PURCHASE(EMVErrorCode.FLASHCARD_ERR_NO_PURCHASE, "Flash card without occor transaction"),
    Error_MESSAGE_FLASHCARD_ERR_PURCHASE_GPO(EMVErrorCode.FLASHCARD_ERR_PURCHASE_GPO, "Flash card GPO error"),
    Error_MESSAGE_FLASHCARD_ERR_LAST_RECORD_NO_RESPONSE(EMVErrorCode.FLASHCARD_ERR_LAST_RECORD_NO_RESPONSE, "The last read record of the flash card is not responding"),
    Error_MESSAGE_FLASHCARD_ERR_NO_GET_PAN(EMVErrorCode.FLASHCARD_ERR_NO_GET_PAN, "Flash card can not get the card number"),
    Error_MESSAGE_FLASHCARD_ERR_PAN_NOT_SAME(EMVErrorCode.FLASHCARD_ERR_PAN_NOT_SAME, "Flash card number is different"),
    Error_MESSAGE_FLASHCARD_ERR_AID_NOT_SAME(EMVErrorCode.FLASHCARD_ERR_AID_NOT_SAME, "Flash card aid is not the same"),
    Error_MESSAGE_FLASHCARD_ERR_PAN_NO_RESPONSE(EMVErrorCode.FLASHCARD_ERR_PAN_NO_RESPONSE, "The last record of the flash card is not responding"),


    Error_MESSAGE_RFERR_BASE(EMVErrorCode.RFERR_BASE, "Preprocessing benchmark error code"),
    Error_MESSAGE_RFERR_PREPROCESS_PARAFILE(EMVErrorCode.RFERR_PREPROCESS_PARAFILE, "Preprocessing parameter file error"),
    Error_MESSAGE_RFERR_PREPROCESS_AMTQUIT(EMVErrorCode.RFERR_PREPROCESS_AMTQUIT, "Preprocessing input amount user exits"),
    Error_MESSAGE_RFERR_PREPROCESS_AMTTIMEOUT(EMVErrorCode.RFERR_PREPROCESS_AMTTIMEOUT, "Preprocessing input amount timeout"),
    Error_MESSAGE_RFERR_PREPROCESS_AMTFAIL(EMVErrorCode.RFERR_PREPROCESS_AMTFAIL, "Preprocessing input amount failed"),
    Error_MESSAGE_RFERR_PREPROCESS_AMTLIMITOVER(EMVErrorCode.RFERR_PREPROCESS_AMTLIMITOVER, "Preprocessed input amount exceeds the limit"),
    Error_MESSAGE_RFERR_PREPROCESS_REQONLINE(EMVErrorCode.RFERR_PREPROCESS_REQONLINE, "Preprocessing requires online, terminal cannot be online"),
    Error_MESSAGE_RFERR_PREPROCESS_NOAID(EMVErrorCode.RFERR_PREPROCESS_NOAID, "AID is 0"),
    Error_MESSAGE_RFERR_ICCDEACTIVE(EMVErrorCode.RFERR_ICCDEACTIVE, "RF card removal failed"),
    Error_MESSAGE_RFERR_ICCRETURNERROR(EMVErrorCode.RFERR_ICCRETURNERROR, "Card returned error"),
    Error_MESSAGE_RFERR_READAPPDATA(EMVErrorCode.RFERR_READAPPDATA, "Failed to read application data"),
    Error_MESSAGE_RFERR_BLKCARD(EMVErrorCode.RFERR_BLKCARD, "Card blacklist"),
    Error_MESSAGE_RFERR_ICCNOEFFECT(EMVErrorCode.RFERR_ICCNOEFFECT, "The card is not valid"),
    Error_MESSAGE_RFERR_ICCEXPIRE(EMVErrorCode.RFERR_ICCEXPIRE, "ard has invalid"),
    Error_MESSAGE_RFERR_DATAAUTH(EMVErrorCode.RFERR_DATAAUTH, "Card data authentication failed"),
    Error_MESSAGE_RFERR_TRACK2EDATA(EMVErrorCode.RFERR_TRACK2EDATA, "Card second magnetic equivalent data failed"),
    Error_MESSAGE_RFERR_ICCFCHECK(EMVErrorCode.RFERR_ICCFCHECK, "Frequency check exceeds limit"),
    Error_MESSAGE_RFERR_ECPURE_CANNOT_ONLINE(EMVErrorCode.RFERR_ECPURE_CANNOT_ONLINE, "Pure electronic cash card can not be online"),
    Error_MESSAGE_RFERR_CARD_DENIAL(EMVErrorCode.RFERR_CARD_DENIAL, "Card rejection"),
    Error_MESSAGE_RFERR_NOODA(EMVErrorCode.RFERR_NOODA, "Card AIP has no data authentication"),
    Error_MESSAGE_RFERR_9F10CID(EMVErrorCode.RFERR_9F10CID, "Card 9F10 return transaction result error"),
    Error_MESSAGE_RFERR_DATAAUTHNOPAN(EMVErrorCode.RFERR_DATAAUTHNOPAN, "Card data authentication without card number information"),
    Error_MESSAGE_RFERR_FDDAFAIL_SUPPBOC(EMVErrorCode.RFERR_FDDAFAIL_SUPPBOC, "FDDA failed, card and terminal support contact PBOC"),
    Error_MESSAGE_RFERR_ODAFAIL_DENIAL(EMVErrorCode.RFERR_ODAFAIL_DENIAL, "ODA failed, terminal refused to trade"),


    Error_MESSAGE_PPERR_BASE(EMVErrorCode.PPERR_BASE, "Paypass benchmark error code"),
    Error_MESSAGE_PPERR_TRANS_LIMITOVER(EMVErrorCode.PPERR_TRANS_LIMITOVER, "transaction usAmount over all Terminal Contactless Transaction Limit"),
    Error_MESSAGE_PPERR_TRACK(EMVErrorCode.PPERR_TRACK, "paypass error track data"),
    Error_MESSAGE_PPERR_TRACK_PCVC3(EMVErrorCode.PPERR_TRACK_PCVC3, "paypass pcvc3"),
    Error_MESSAGE_PPERR_TRACK_PUNATC(EMVErrorCode.PPERR_TRACK_PUNATC, "paypass punatc"),
    Error_MESSAGE_PPERR_TRACK_NATC(EMVErrorCode.EMV_ERR_READCONFIG, "paypass natc"),
    Error_MESSAGE_PPERR_TRACK_KLTT(EMVErrorCode.PPERR_TRACK_KLTT, "k_track < t_track"),
    Error_MESSAGE_PPERR_TRACK_NUN(EMVErrorCode.PPERR_TRACK_NUN, "track data wrong unpredictable number"),
    Error_MESSAGE_PPERR_TRACK1_PAN(EMVErrorCode.PPERR_TRACK1_PAN, "not the same as track2"),
    Error_MESSAGE_PPERR_TRACK1_EXPIREDATE(EMVErrorCode.PPERR_TRACK1_EXPIREDATE, "not the same as track2"),
    Error_MESSAGE_PPERR_CCC_CMD(EMVErrorCode.PPERR_CCC_CMD, "compute cryptographic checksum error"),
    Error_MESSAGE_PPERR_CCC_RESPONSE(EMVErrorCode.PPERR_CCC_RESPONSE, "compute cryptographic checksum response error"),
    Error_MESSAGE_PPERR_CCC_UDOL_NO9F6A(EMVErrorCode.PPERR_CCC_UDOL_NO9F6A, "UDOL NO 9F6A"),
    Error_MESSAGE_PPERR_CCC_TRACK1CVC3(EMVErrorCode.PPERR_CCC_TRACK1CVC3, "CCC command return track2 cvc3 error"),
    Error_MESSAGE_PPERR_CCC_ATC(EMVErrorCode.PPERR_CCC_ATC, "CCC command return atc error"),
    Error_MESSAGE_PPERR_CCC_NODEF_UDOL(EMVErrorCode.PPERR_CCC_NODEF_UDOL, "NO default UDOL"),
    Error_MESSAGE_PPERR_CCC_DOLPACKET(EMVErrorCode.PPERR_CCC_DOLPACKET, "UDOL pack error"),
    Error_MESSAGE_PPERR_PP_ENTERPIN(EMVErrorCode.PPERR_PP_ENTERPIN, "input pin error"),
    Error_MESSAGE_PPERR_READAPPDATA(EMVErrorCode.PPERR_READAPPDATA, "read app  error"),
    Error_MESSAGE_PPERR_PREPROCESS_AMTQUIT(EMVErrorCode.PPERR_PREPROCESS_AMTQUIT, "Preprocessing input amount user exits"),
    Error_MESSAGE_PPERR_PREPROCESS_AMTTIMEOUT(EMVErrorCode.PPERR_PREPROCESS_AMTTIMEOUT, "Preprocessing input amount timeout"),
    Error_MESSAGE_PPERR_PREPROCESS_AMTFAIL(EMVErrorCode.PPERR_PREPROCESS_AMTFAIL, "Preprocessing input amount failed"),
    Error_MESSAGE_PPERR_SDAFAIL(EMVErrorCode.PPERR_SDAFAIL, "SDA failed transaction terminate"),
    Error_MESSAGE_PPERR_TRACK1_LEN(EMVErrorCode.PPERR_TRACK1_LEN, "Track1 length error"),
    Error_MESSAGE_PPERR_TRACK2_LEN(EMVErrorCode.PPERR_TRACK2_LEN, "Track2 length error"),
    Error_MESSAGE_PPERR_SAVEDATA(EMVErrorCode.PPERR_SAVEDATA, "save data error"),
    Error_MESSAGE_PPERR_READPARAM(EMVErrorCode.PPERR_READPARAM, "read param config error"),
    Error_MESSAGE_PPERR_CCC_PCII(EMVErrorCode.PPERR_CCC_PCII, "CCC command return PCII error"),
    Error_MESSAGE_PPERR_CCC_TRACK_DATA_MISSING(EMVErrorCode.PPERR_CCC_TRACK_DATA_MISSING, "Used to specifically indicate data loss errors"),


    Error_MESSAGE_PWERR_BASE(EMVErrorCode.PWERR_BASE, "Paywave benchmark error code"),
    Error_MESSAGE_PWERR_9F26(EMVErrorCode.PWERR_9F26, "error or no 9F26 in read record command"),
    Error_MESSAGE_PWERR_9F36(EMVErrorCode.PWERR_9F36, "error or no 9F36 in read record command"),
    Error_MESSAGE_PWERR_9F10(EMVErrorCode.PWERR_9F10, "error or no 9F10in read record command"),
    Error_MESSAGE_PWERR_57(EMVErrorCode.PWERR_57, "error or no 57 in read record command"),
    Error_MESSAGE_PWERR_9F27(EMVErrorCode.PWERR_9F27, "error or no 9F27 in read record command"),
    Error_MESSAGE_PWERR_INTER_TRANS(EMVErrorCode.PWERR_INTER_TRANS, "international transaction"),
    Error_MESSAGE_PWERR_NO9F74(EMVErrorCode.PWERR_NO9F74, "Did not return 9F74"),
    Error_MESSAGE_PWERR_PW_ENTERPIN(EMVErrorCode.PWERR_PW_ENTERPIN, "define request online error"),
    Error_MESSAGE_PWERR_AIP_NOSUPPORTFDDA(EMVErrorCode.PWERR_AIP_NOSUPPORTFDDA, "aip no support fdda"),


    Error_MESSAGE_RUERR_BASE(EMVErrorCode.RUERR_BASE, "Rupay benchmark error code"),
    Error_MESSAGE_RUERR_SERVICE_KCV_WRONG(EMVErrorCode.RUERR_SERVICE_KCV_WRONG, "Rupay KCV error"),


    Error_MESSAGE_MIR_BASE(EMVErrorCode.MIR_BASE, "MIR benchmark error code"),
    Error_MESSAGE_MIR_PROTOCOLWRONG(EMVErrorCode.MIR_PROTOCOLWRONG, "MIR protocol value error"),
    Error_MESSAGE_MIR_AIP_NOSUPPORT_EMV(EMVErrorCode.MIR_AIP_NOSUPPORT_EMV, "MIR aip does not support EMV mode"),
    Error_MESSAGE_MIR_NOHAVE_DF6F(EMVErrorCode.MIR_NOHAVE_DF6F, "MIR Protocol 2 does not have DF6F ODOL"),
    Error_MESSAGE_MIR_DF6F_WRONG(EMVErrorCode.MIR_DF6F_WRONG, "MIR Protocol 2 DF6F ODOL error"),
    Error_MESSAGE_MIR_SERVICE_NOTALLOW(EMVErrorCode.MIR_ESRVICE_NOTALLOW, "MIR protocol 2 service not allowed"),
    Error_MESSAGE_MIR_SDADMISSING(EMVErrorCode.MIR_SDADMISSING, "MIR without SDAD"),
    Error_MESSAGE_MIR_TRANSPERFORM_BADSW(EMVErrorCode.MIR_TRANSPERFORM_BADSW, "MIR executes transaction commands without returning 9000"),
    Error_MESSAGE_MIR_TRANSPERFORM_NOT77(EMVErrorCode.MIR_TRANSPERFORM_NOT77, "MIR executes transaction commands without returning 77 templates"),
    Error_MESSAGE_MIR_TRANSPERFORM_77NOT9F27(EMVErrorCode.MIR_TRANSPERFORM_77NOT9F27, "MIR executes transaction commands without returning 9F27"),
    Error_MESSAGE_MIR_TRANSPERFORM_77NOT9F36(EMVErrorCode.MIR_TRANSPERFORM_77NOT9F36, "MIR executes transaction commands without returning 9F36"),
    Error_MESSAGEMIR_TRANSPERFORM_77NOT9F71(EMVErrorCode.MIR_TRANSPERFORM_77NOT9F71, "MIR executes transaction commands without returning 9F71"),
    Error_MESSAGE_MIR_TRANSCPMPLETE_BADSW(EMVErrorCode.MIR_TRANSCPMPLETE_BADSW, "MIR executes transaction commands without returning 9000"),
    Error_MESSAGE_MIR_TRANSCPMPLETE_NO9F26(EMVErrorCode.MIR_TRANSCPMPLETE_NO9F26, "MIR executes transaction commands without returning 9F26"),
    Error_MESSAGE_MIR_TRANSPERFORM_NORECOVRY(EMVErrorCode.MIR_TRANSPERFORM_NORECOVRY, "MIR does not support recovery when executing transaction commands"),
    Error_MESSAGE_MIR_TRANSPERFORM_LIMIT(EMVErrorCode.MIR_TRANSPERFORM_LIMIT, "MIR Executes Transaction Command Restoration Over Restriction"),
    Error_MESSAGE_MIR_TRANSCOMPLETE_NORECOVRY(EMVErrorCode.MIR_TRANSCOMPLETE_NORECOVRY, "MIR Executes Transaction Completion Command does not support recovery"),
    Error_MESSAGE_MIR_TRANSCOMPLETE_LIMIT(EMVErrorCode.MIR_TRANSCOMPLETE_LIMIT, "MIR Executes Transaction Completion Command Restore Over Restriction"),
    Error_MESSAGE_MIR_TRANSREADRECORD_NORECOVRY(EMVErrorCode.MIR_TRANSREADRECORD_NORECOVRY, "MIR Read Record Command does not support recovery"),
    Error_MESSAGE_MIR_TRANSREADRECORD_LIMIT(EMVErrorCode.MIR_TRANSREADRECORD_LIMIT, "MIR Read Record Command Restore Over Restriction"),


    Error_MESSAGE_CAPKERR_BASE(EMVErrorCode.CAPKERR_BASE, "Public key file operation benchmark error code"),
    Error_MESSAGE_CAPKERR_FILEOPEN(EMVErrorCode.CAPKERR_FILEOPEN, "File open error"),
    Error_MESSAGE_CAPKERR_FILEWRITE(EMVErrorCode.CAPKERR_FILEWRITE, "write file error"),
    Error_MESSAGE_CAPKERR_FILEREAD(EMVErrorCode.CAPKERR_FILEREAD, "Read file error"),
    Error_MESSAGE_CAPKERR_CHKSUM(EMVErrorCode.CAPKERR_CHKSUM, "Public key checksum error"),
    Error_MESSAGE_CAPKERR_LOST(EMVErrorCode.CAPKERR_LOST, "This public key was not foundn"),
    Error_MESSAGE_CAPKERR_PARAM(EMVErrorCode.CAPKERR_PARAM, "Parameter error"),
    Error_MESSAGE_CAPKERR_FILELEN(EMVErrorCode.CAPKERR_FILELEN, "File length error"),

    Error_MESSAGE_LIST_BASE(EMVErrorCode.LIST_BASE, "Public key collection list and card blacklist file operation benchmark error code"),
    Error_MESSAGE_LIST_FILEOPEN(EMVErrorCode.LIST_FILEOPEN, "File open error"),
    Error_MESSAGE_LIST_FILEWRITE(EMVErrorCode.LIST_FILEWRITE, "write file error"),
    Error_MESSAGE_LIST_FILEREAD(EMVErrorCode.LIST_FILEREAD, "Read file error"),
    Error_MESSAGE_LIST_LEN_EXCEED(EMVErrorCode.LIST_LEN_EXCEED, "Data length is exceeds limit"),
    Error_MESSAGE_LIST_RECORD_NOFOUND(EMVErrorCode.LIST_RECORD_NOFOUND, "Without find the corresponding record"),
    Error_MESSAGE_LIST_PARAM(EMVErrorCode.LIST_PARAM, "Parameter error"),
    Error_MESSAGE_LIST_FILELEN(EMVErrorCode.LIST_FILELEN,"file length error"),

    Error_MESSAGE_AIDERR_BASE(EMVErrorCode.AIDERR_BASE, "AID parameter file operation benchmark error code"),
    Error_MESSAGE_AIDERR_FILEOPEN(EMVErrorCode.AIDERR_FILEOPEN, "File open error"),
    Error_MESSAGE_AIDERR_FILEWRITE(EMVErrorCode.AIDERR_FILEWRITE, "write file error"),
    Error_MESSAGE_AIDERR_FILEREAD(EMVErrorCode.AIDERR_FILEREAD, "Read file error"),
    Error_MESSAGE_AIDERR_CHKSUM(EMVErrorCode.AIDERR_CHKSUM, "Public key checksum error"),
    Error_MESSAGE_AIDERR_LOST(EMVErrorCode.AIDERR_LOST, "This AID was not found"),
    Error_MESSAGE_AIDERR_PARAM(EMVErrorCode.AIDERR_PARAM, "Parameter error"),
    Error_MESSAGE_AIDERR_FILELEN(EMVErrorCode.AIDERR_FILELEN, "File length error"),
    Error_MESSAGE_AIDERR_UPTAID(EMVErrorCode.AIDERR_UPTAID, "Synchronous update of AID corresponding data fails when updating terminal configuration parameters"),
    Error_MESSAGE_AIDERR_PARSE(EMVErrorCode.AIDERR_PARSE, "AID parsing failed"),
    Error_MESSAGE_AIDERR_DISABLE(EMVErrorCode.AIDERR_DISABLE, "AID is not available");

    private Integer keyId;

    private String message;

    EMVErrorMessage(Integer keyId, String message) {
        this.keyId = keyId;
        this.message = message;
    }

    public static String getMessageByKeyId(Integer keyId) {
        EMVErrorMessage[] errorMessageEnums = values();
        for (EMVErrorMessage errormessage : errorMessageEnums) {
            if (errormessage.getKeyId().equals(keyId)) {
                return errormessage.getMessage();
            }
        }
        return null;
    }


    public Integer getKeyId() {
        return keyId;
    }


    public String getMessage() {
        return message;
    }


}






