include ':nmjs-api'
include ':libraryModule'
include ':devicemodule'
include ':meEMVModule'
include ':scanmodule'

include ':mesdk'
include ':buildTask'
include ':SDKDemo'

//include ':testscanner'
//include ':buildTaskModule'
//include ':extPinPadEmvModule'
//include ':usbtest'
include 'SimpleSDKDemo'
