<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>com.newland.mtype</groupId>
    <artifactId>nmjs</artifactId>
    <version>${mesdk.version}-RELEASE</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <name>Newland MType Java SDK deviceModule</name>
  <artifactId>deviceModule</artifactId>
  <packaging>apklib</packaging>
  <build>
	<plugins>
		<plugin>
		  <groupId>org.apache.maven.plugins</groupId>
		  <artifactId>maven-javadoc-plugin</artifactId>
		  <version>2.9</version>
		  <configuration>
		    <excludePackageNames>
				com.newland.sdk.module.cardreader.K21CardReaderEvent,com.newland.sdk.module.pin.PinInputExtListener,
            </excludePackageNames>
		    <additionalJOptions>
		    <additionalJOption>-J-Duser.language=en_US</additionalJOption>
		    </additionalJOptions>
		  </configuration>
		</plugin>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-install-plugin</artifactId>
			<version>2.3.1</version>
			<executions>
				<execution> <!-- 废掉默认声称的apklib,而使用proguard生成的混淆包进行安装 -->
					<id>default-install</id>
					<phase>none</phase>
				</execution>
				<execution><!-- 安装proguard生成的混淆包 -->
					<id>custom-install</id>
					<phase>install</phase>
					<goals>
						<goal>install-file</goal>
					</goals>
					<configuration>
						<file>${project.build.directory}/deviceModule-${project.version}_obfuscated.jar</file>
						<generatePom>false</generatePom>
						<pomFile>pom.xml</pomFile>
						<packaging>jar</packaging>
						<version>${project.version}</version>
					</configuration>
				</execution>
			</executions>
		</plugin>
			<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<executions>
					<execution>
						<phase>install</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<tasks>
								<move file="${basedir}/target/deviceModule-${project.version}_obfuscated.jar"
									tofile="${basedir}/target/deviceModule-${project.version}.jar" />
							</tasks>
						</configuration>
					</execution>
				</executions>
			</plugin>
		<plugin>
			<groupId>com.jayway.maven.plugins.android.generation2</groupId>
			<artifactId>android-maven-plugin</artifactId>
			<configuration>
				<proguard>
					<skip>false</skip>
					<jvmArguments>
						<jvmArgument>-Xms256m</jvmArgument>
						<jvmArgument>-Xmx512m</jvmArgument>
					</jvmArguments>
				</proguard>
			</configuration>
		</plugin>
      
    </plugins>
    <sourceDirectory>src</sourceDirectory>
    <testSourceDirectory>test</testSourceDirectory>
  </build>
  <dependencies>
      <dependency>
          <groupId>com.google.android</groupId>
          <artifactId>android</artifactId>
          <scope>provided</scope>
      </dependency>
      <dependency>
          <groupId>com.newland.mtype</groupId>
          <artifactId>mtype-sdk-api</artifactId>
          <version>${project.version}</version>
          <type>jar</type>
          <scope>provided</scope>
      </dependency>
    <dependency>
    <!-- Support library (aka compatibility library) from the central repository as well
      note that this uses default scope (NOT provided) since the library will need to be added to your apk -->
      <groupId>com.google.android</groupId>
      <artifactId>support-v4</artifactId>
      <scope>provided</scope>
    </dependency>
	  <dependency>
		  <groupId>com.android.support</groupId>
		  <artifactId>support-annotations</artifactId>
		  <version>28.0.0</version>
		  <scope>provided</scope>
	  </dependency>
	  <dependency>
		  <groupId>com.newland.rkl</groupId>
		  <artifactId>rkl</artifactId>
		  <version>1.1.0</version>
		  <scope>provided</scope>
	  </dependency>
<!--	  <dependency>-->
<!--		  <groupId>com.newland</groupId>-->
<!--		  <artifactId>newland</artifactId>-->
<!--		  <scope>provided</scope>-->
<!--	  </dependency>-->
  </dependencies>
</project>
