package com.newland.ndk.h;

public enum EM_SYS_HWINFO {
	SYS_HWINFO_GET_POS_TYPE,
	SYS_HWINFO_GET_HARDWARE_INFO,
	SYS_HWINFO_GET_BIOS_VER,
	SYS_HWINFO_GET_POS_USN,
	SYS_HWINFO_GET_POS_PSN,
	SYS_HWINFO_GET_BOARD_VER,
	SYS_HWINFO_GET_CREDITCARD_COUNT,
	SYS_HWINFO_GET_PRN_LEN,
	SYS_HWINFO_GET_POS_RUNTIME,
	SYS_HWINFO_GET_KEY_COUNT,
	SYS_HWINFO_GET_CPU_TYPE,
	SYS_HWINFO_GET_BOOT_VER,
	SYS_HWINFO_GET_BOARD_NUMBER,
	SYS_HWINFO_GET_KLA1_VER,
	SYS_HWINFO_GET_KLA2_VER,
	SYS_HWINFO_GET_POS_TUSN,
	SYS_HWINFO_GET_RFID_CHIP_TYPE,
	SYS_HWINFO_GET_MAX,
}
