package com.newland.nsdk.externaldevice.display;


import com.newland.nsdk.core.api.common.exception.NSDKException;
import com.newland.nsdk.core.api.common.utils.ISOUtils;
import com.newland.nsdk.core.api.external.communication.ExternalCommunicator;
import com.newland.nsdk.core.api.external.display.AlignType;
import com.newland.nsdk.core.api.external.display.DiaplayQRImageParameters;
import com.newland.nsdk.core.api.external.display.DisplayListener;
import com.newland.nsdk.core.api.external.display.FontSize;
import com.newland.nsdk.core.api.external.display.QRErrorCorrectLevel;
import com.newland.nsdk.core.api.external.display.QRMask;
import com.newland.nsdk.core.api.external.display.QRTextPosition;
import com.newland.nsdk.core.external.command.communication.ExternalCommunicationManager;
import com.newland.nsdk.core.external.command.communication.mock.MockExternalCommunicator;
import com.newland.nsdk.core.external.command.display.ExternalDisplayModule;
import com.newland.nsdk.core.external.ExtDisplayImpl;

import org.junit.Before;
import org.junit.Test;

public class ExternalDisplayModuleTest {

    private ExternalDisplayModule displayModule = new ExternalDisplayModule();
    private ExtDisplayImpl extDisplay = new ExtDisplayImpl();

    @Before
    public void init(){
        ExternalCommunicator communicator = new MockExternalCommunicator();
        ExternalCommunicationManager.getInstance().setCommunicator(communicator);
    }

    @Test
    public void setDisplayMode(){
        try{
            displayModule.setDisplayMode((byte)-100);
        }catch (NSDKException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void displayText(){
        String[] str = {"ABCD","","abcd"};
        try{
            displayModule.displayText(str);
        }catch (NSDKException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void displayImage(){
        byte[] imageData = {00,00};
        try{
            displayModule.displayImage((byte)2,imageData,0,0);
        }catch (NSDKException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void loadImage(){
        //byte[] imageData = {00,01};
        //byte[] imageData = {};
        byte[] imageData = new byte[0];
        try{
            displayModule.loadImage((byte)2,imageData);
        }catch (NSDKException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void setFontColor(){
        try{
            displayModule.setFontColor(0x00ff,(byte)0);
//            displayModule.setFontColor(9887889,0);
        }catch (NSDKException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void clearScreen(){
        try{
            displayModule.clearScreen();
        }catch (NSDKException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void setFontSize(){
        try{
            displayModule.setFontSize(FontSize.LARGE);
        }catch (NSDKException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void setDisplayDirection(){
        try{
            displayModule.setDisplayDirection(AlignType.CENTER);
        }catch (NSDKException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void displayChinese(){
        byte[] chinese = {0x00,0x11,0x22};
        try{
            //displayModule.displayChinese(0, CNTextNotifyType.TRANSACTION_SUCCESS,null,2,2,2);
            //displayModule.displayChinese(1, CNTextNotifyType.TRANSACTION_SUCCESS,null,2,2,2);
            displayModule.displayChinese((byte)1, null,chinese,2,2,2);
        }catch (NSDKException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void optionSelect(){
        String[] str = {"ABCD","","abcd"};
        try{
            displayModule.optionSelect(str);
        }catch (NSDKException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void displayPicture(){
        byte[] imageData = {00,00};
        try{
            displayModule.displayPicture(1,1,40,60,1,2,imageData);
        }catch (NSDKException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void displayQRCode(){
        byte[]tdata = {0x30,0x33,0x67};
        byte[]pdata = {0x30,0x33,0x67};
        DiaplayQRImageParameters parameter = new DiaplayQRImageParameters();
        parameter.setLevel(QRErrorCorrectLevel.LEVEL_1);
        parameter.setMask(QRMask.MASK_1);
        parameter.setVersion((byte)0);
        parameter.setAutoCenter(true);
        parameter.setXCoordinate((byte)1);
        parameter.setYCoordinate((byte)1);
        parameter.setPosition(QRTextPosition.BOTTOM);
        parameter.setTextData(tdata);
        try{
            displayModule.displayQRCode(pdata, parameter);
        }catch (NSDKException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void displayColorImage(){
        DisplayListener listener = new DisplayListener() {
            @Override
            public void onError(int i, String s) {
                System.out.println("Display color image error code: " + i);
                System.out.println("Display color image error mesage: " + s);
            }

            @Override
            public void onSuccess() {
                System.out.println("Display color image successfully.");
            }
        };
        byte[] imageData = ISOUtils.hex2byte("424D8E040000000000003E000000280000005D0000005C000000010001000000000050040000C40E0000C40E0000000000000000000000000000FFFFFF00FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFF7FFFFEFFFFFFFFF8FFFFFFFF3FFFFEFFFFFFFFF8FFFFFFFF7FFFFEFFFFFFFFF8FFFFFFFF7FFFFEFFFFFFFFF8FFFFFFFF7FFFFEFFFFFFFFF8FFFFFFFF7FFFFEFFFFFFFFF8FFFFFFFF3FFFFEFFFFFFFFF8FFFFFFFF3FFFFEFFFFFFFFF8FFFFFFFF3FFFC6FFFFFFFFF8FFFFFFFF203C02FFFFFFFFF8FFFFFFFF0710FEFFFFFFFFF8FFFFFFFF3FC7FEFFFFFFFFF8FFFFFFFF3F9FC6FFFFFFFFF8FFFFFFFF203F00FFFFFFFFF8FFFFFFFF007C38FFFFFFFFF8FFFFFFFF2FF0F8FFFFFFFFF8FFFFFFFF2FE238FFFFFFFFF8FFFFFFFF278F027FFFFFFFF8FFFFFFFF303FCE03FFFFFFF8FFFFFFFE3FFFFFF0FFFFFFF8FFFFFFF87FFFFFFE3FFFFFF8FFFFFFF1FFFFFFFF9FFFFFF8FFFFFFE7FFFFFFFFC7FFFFF8FFFFFF8FFFFFFFFFE3FFFFF8FFFFFF3FFFFFFFFFF9FFFFF8FFFFFE7FFFFFFFFFF9FFFFF8FFFFFE7FFFFFFFFFFCFFFFF8FFFFFDFFFFFFFFFFFE7FFFF8FFFFF9FFFFFFFFFFFE7FFFF8FFFFF3FFFFFFFFFFFF3FFFF8FFFFF3FFFFC001FFFF3FFFF8FFFFF7FFFFC001FFFF9FFFF8FFFFE7FFFFFFFFFFFF9FFFF8FFFFEFFFFFFFFFFFFF9FFFF8FFFFEFFFFFFFFFFFFFDFFFF8FFFFCFFFFFFFFFFFFFDFFFF8FFFFCFFFFFFFFFFFFFDFFFF8FFFFCFFFFFFFFFFFFFCFFFF8FFFFDFFFFFFFFFFFFFCFFFF8FFFFDFFFFFFFFFFFFFCFFFF8FFFFDFFFFFFFFFFFFFCFFFF8FFFFDFFFFFFFFFE7FFDFFFF8FFFFDFFFFFFFFFC3FFDFFFF8FFFFCFFF8FFFFFC3FFDFFFF8FFFFCFFF0FFFFFE7FF9FFFF8FFFFCFFF0FFFFFFFFF9FFFF8FFFFCFFFFFFFFFFFFFBFFFF8FFFFEFFFFFFFFFFFFF3FFFF8FFFFEFF0007FF800FF3FFFF8FFFFE7FFFF3FF9FFFE7FFFF8FFFFE7FFFF9FFBFFFE7FFFF8FFFFF3FFFFBFFFFFFCFFFFF8FFFFF3FFFFFFFFFFFDFFFFF8FFFFF9FFFFFFFFFFF9FFFFF8FFFFF9FFFFFFFFFFF3FFFFF8FFFFFCFFFFFFFFFFE7FFFFF8FFFFFE7FFFFFFFFFCFFFFFF8FFFFFE3FFFFFFFFF9FFFFFF8FFFFFF1FFFFFFFFE3FFFFFF8FFFFFFCFFFFFFFF8FFFFFFF8FFFFFFE7FFFFFFF1FFFFFFF8FFFFFFF1FFFFFF87FFFFFFF8FFFFFFF9FFFFFC1FFFFFFFF8FFFFFFF3F8FE00FFFFFFFFF8FFFFFFF7F00007FFFFFFFFF8FFFFFFE7F3F9E7FFFFFFFFF8FFFFFFEFF7F9E7FFFFFFFFF8FFFFFFCFE7F9E7FFFFFFFFF8FFFFFFDFE7F9E7FFFFFFFFF8FFFFFF9FEFFBE7FFFFFFFFF8FFFFFFBFCFFBE7FFFFFFFFF8FFFFFFBFDFFBE7FFFFFFFFF8FFFFFF3FDFF3E7FFFFFFFFF8FFFFFF3F9FF3EFFFFFFFFFF8FFFFFF3FBFF3EFFFFFFFFFF8FFFFFF7F3FF3EFFFFFFFFFF8FFFFFF3E7FF3EFFFFFFFFFF8FFFFFF3E7FF3CFFFFFFFFFF8FFFFFF9CFFF3CFFFFFFFFFF8FFFFFFC1FFF39FFFFFFFFFF8FFFFFFFFFFF81FFFFFFFFFF8FFFFFFFFFFFC7FFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8424D8E040000000000003E000000280000005D0000005C000000010001000000000050040000C40E0000C40E0000000000000000000000000000FFFFFF00FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFF7FFFFEFFFFFFFFF8FFFFFFFF3FFFFEFFFFFFFFF8FFFFFFFF7FFFFEFFFFFFFFF8FFFFFFFF7FFFFEFFFFFFFFF8FFFFFFFF7FFFFEFFFFFFFFF8FFFFFFFF7FFFFEFFFFFFFFF8FFFFFFFF3FFFFEFFFFFFFFF8FFFFFFFF3FFFFEFFFFFFFFF8FFFFFFFF3FFFC6FFFFFFFFF8FFFFFFFF203C02FFFFFFFFF8FFFFFFFF0710FEFFFFFFFFF8FFFFFFFF3FC7FEFFFFFFFFF8FFFFFFFF3F9FC6FFFFFFFFF8FFFFFFFF203F00FFFFFFFFF8FFFFFFFF007C38FFFFFFFFF8FFFFFFFF2FF0F8FFFFFFFFF8FFFFFFFF2FE238FFFFFFFFF8FFFFFFFF278F027FFFFFFFF8FFFFFFFF303FCE03FFFFFFF8FFFFFFFE3FFFFFF0FFFFFFF8FFFFFFF87FFFFFFE3FFFFFF8FFFFFFF1FFFFFFFF9FFFFFF8FFFFFFE7FFFFFFFFC7FFFFF8FFFFFF8FFFFFFFFFE3FFFFF8FFFFFF3FFFFFFFFFF9FFFFF8FFFFFE7FFFFFFFFFF9FFFFF8FFFFFE7FFFFFFFFFFCFFFFF8FFFFFDFFFFFFFFFFFE7FFFF8FFFFF9FFFFFFFFFFFE7FFFF8FFFFF3FFFFFFFFFFFF3FFFF8FFFFF3FFFFC001FFFF3FFFF8FFFFF7FFFFC001FFFF9FFFF8FFFFE7FFFFFFFFFFFF9FFFF8FFFFEFFFFFFFFFFFFF9FFFF8FFFFEFFFFFFFFFFFFFDFFFF8FFFFCFFFFFFFFFFFFFDFFFF8FFFFCFFFFFFFFFFFFFDFFFF8FFFFCFFFFFFFFFFFFFCFFFF8FFFFDFFFFFFFFFFFFFCFFFF8FFFFDFFFFFFFFFFFFFCFFFF8FFFFDFFFFFFFFFFFFFCFFFF8FFFFDFFFFFFFFFE7FFDFFFF8FFFFDFFFFFFFFFC3FFDFFFF8FFFFCFFF8FFFFFC3FFDFFFF8FFFFCFFF0FFFFFE7FF9FFFF8FFFFCFFF0FFFFFFFFF9FFFF8FFFFCFFFFFFFFFFFFFBFFFF8FFFFEFFFFFFFFFFFFF3FFFF8FFFFEFF0007FF800FF3FFFF8FFFFE7FFFF3FF9FFFE7FFFF8FFFFE7FFFF9FFBFFFE7FFFF8FFFFF3FFFFBFFFFFFCFFFFF8FFFFF3FFFFFFFFFFFDFFFFF8FFFFF9FFFFFFFFFFF9FFFFF8FFFFF9FFFFFFFFFFF3FFFFF8FFFFFCFFFFFFFFFFE7FFFFF8FFFFFE7FFFFFFFFFCFFFFFF8FFFFFE3FFFFFFFFF9FFFFFF8FFFFFF1FFFFFFFFE3FFFFFF8FFFFFFCFFFFFFFF8FFFFFFF8FFFFFFE7FFFFFFF1FFFFFFF8FFFFFFF1FFFFFF87FFFFFFF8FFFFFFF9FFFFFC1FFFFFFFF8FFFFFFF3F8FE00FFFFFFFFF8FFFFFFF7F00007FFFFFFFFF8FFFFFFE7F3F9E7FFFFFFFFF8FFFFFFEFF7F9E7FFFFFFFFF8FFFFFFCFE7F9E7FFFFFFFFF8FFFFFFDFE7F9E7FFFFFFFFF8FFFFFF9FEFFBE7FFFFFFFFF8FFFFFFBFCFFBE7FFFFFFFFF8FFFFFFBFDFFBE7FFFFFFFFF8FFFFFF3FDFF3E7FFFFFFFFF8FFFFFF3F9FF3EFFFFFFFFFF8FFFFFF3FBFF3EFFFFFFFFFF8FFFFFF7F3FF3EFFFFFFFFFF8FFFFFF3E7FF3EFFFFFFFFFF8FFFFFF3E7FF3CFFFFFFFFFF8FFFFFF9CFFF3CFFFFFFFFFF8FFFFFFC1FFF39FFFFFFFFFF8FFFFFFFFFFF81FFFFFFFFFF8FFFFFFFFFFFC7FFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8424D8E040000000000003E000000280000005D0000005C000000010001000000000050040000C40E0000C40E0000000000000000000000000000FFFFFF00FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFF7FFFFEFFFFFFFFF8FFFFFFFF3FFFFEFFFFFFFFF8FFFFFFFF7FFFFEFFFFFFFFF8FFFFFFFF7FFFFEFFFFFFFFF8FFFFFFFF7FFFFEFFFFFFFFF8FFFFFFFF7FFFFEFFFFFFFFF8FFFFFFFF3FFFFEFFFFFFFFF8FFFFFFFF3FFFFEFFFFFFFFF8FFFFFFFF3FFFC6FFFFFFFFF8FFFFFFFF203C02FFFFFFFFF8FFFFFFFF0710FEFFFFFFFFF8FFFFFFFF3FC7FEFFFFFFFFF8FFFFFFFF3F9FC6FFFFFFFFF8FFFFFFFF203F00FFFFFFFFF8FFFFFFFF007C38FFFFFFFFF8FFFFFFFF2FF0F8FFFFFFFFF8FFFFFFFF2FE238FFFFFFFFF8FFFFFFFF278F027FFFFFFFF8FFFFFFFF303FCE03FFFFFFF8FFFFFFFE3FFFFFF0FFFFFFF8FFFFFFF87FFFFFFE3FFFFFF8FFFFFFF1FFFFFFFF9FFFFFF8FFFFFFE7FFFFFFFFC7FFFFF8FFFFFF8FFFFFFFFFE3FFFFF8FFFFFF3FFFFFFFFFF9FFFFF8FFFFFE7FFFFFFFFFF9FFFFF8FFFFFE7FFFFFFFFFFCFFFFF8FFFFFDFFFFFFFFFFFE7FFFF8FFFFF9FFFFFFFFFFFE7FFFF8FFFFF3FFFFFFFFFFFF3FFFF8FFFFF3FFFFC001FFFF3FFFF8FFFFF7FFFFC001FFFF9FFFF8FFFFE7FFFFFFFFFFFF9FFFF8FFFFEFFFFFFFFFFFFF9FFFF8FFFFEFFFFFFFFFFFFFDFFFF8FFFFCFFFFFFFFFFFFFDFFFF8FFFFCFFFFFFFFFFFFFDFFFF8FFFFCFFFFFFFFFFFFFCFFFF8FFFFDFFFFFFFFFFFFFCFFFF8FFFFDFFFFFFFFFFFFFCFFFF8FFFFDFFFFFFFFFFFFFCFFFF8FFFFDFFFFFFFFFE7FFDFFFF8FFFFDFFFFFFFFFC3FFDFFFF8FFFFCFFF8FFFFFC3FFDFFFF8FFFFCFFF0FFFFFE7FF9FFFF8FFFFCFFF0FFFFFFFFF9FFFF8FFFFCFFFFFFFFFFFFFBFFFF8FFFFEFFFFFFFFFFFFF3FFFF8FFFFEFF0007FF800FF3FFFF8FFFFE7FFFF3FF9FFFE7FFFF8FFFFE7FFFF9FFBFFFE7FFFF8FFFFF3FFFFBFFFFFFCFFFFF8FFFFF3FFFFFFFFFFFDFFFFF8FFFFF9FFFFFFFFFFF9FFFFF8FFFFF9FFFFFFFFFFF3FFFFF8FFFFFCFFFFFFFFFFE7FFFFF8FFFFFE7FFFFFFFFFCFFFFFF8FFFFFE3FFFFFFFFF9FFFFFF8FFFFFF1FFFFFFFFE3FFFFFF8FFFFFFCFFFFFFFF8FFFFFFF8FFFFFFE7FFFFFFF1FFFFFFF8FFFFFFF1FFFFFF87FFFFFFF8FFFFFFF9FFFFFC1FFFFFFFF8FFFFFFF3F8FE00FFFFFFFFF8FFFFFFF7F00007FFFFFFFFF8FFFFFFE7F3F9E7FFFFFFFFF8FFFFFFEFF7F9E7FFFFFFFFF8FFFFFFCFE7F9E7FFFFFFFFF8FFFFFFDFE7F9E7FFFFFFFFF8FFFFFF9FEFFBE7FFFFFFFFF8FFFFFFBFCFFBE7FFFFFFFFF8FFFFFFBFDFFBE7FFFFFFFFF8FFFFFF3FDFF3E7FFFFFFFFF8FFFFFF3F9FF3EFFFFFFFFFF8FFFFFF3FBFF3EFFFFFFFFFF8FFFFFF7F3FF3EFFFFFFFFFF8FFFFFF3E7FF3EFFFFFFFFFF8FFFFFF3E7FF3CFFFFFFFFFF8FFFFFF9CFFF3CFFFFFFFFFF8FFFFFFC1FFF39FFFFFFFFFF8FFFFFFFFFFF81FFFFFFFFFF8FFFFFFFFFFFC7FFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFF8");
        try {
            extDisplay.loadImage((byte) 1, imageData, listener);
            Thread.sleep(1000000);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
