package com.newland.nsdk.core.api.common.crypto;

/**
 * Container for the result of an AES-GCM encryption operation.
 */
public class GCMCipherOut extends CipherOutput {

    /**
     * The Authentication Tag generated during encryption.
     * <p>
     * This tag allows the receiver to verify the integrity and authenticity of the
     * encrypted data during decryption.
     * </p>
     */
    byte[] authTag = null;

    /**
     * Constructs a new GCMCipherOut object.
     *
     * @param data    The encrypted data.
     * @param ksn  KSN when it is DUKPT encryption/decryption.
     * @param authTag The authentication tag generated by the GCM algorithm.
     */
    public GCMCipherOut(byte[] data, byte[] ksn, byte[] authTag) {
        super(data, ksn);
        this.authTag = authTag;
    }

    /**
     * Gets the generated Authentication Tag.
     * <p>
     * <strong>Important:</strong> This tag must be preserved and passed to the decryption
     * routine alongside the ciphertext and IV.
     * </p>
     *
     * @return the authentication tag byte array.
     */
    public byte[] getAuthTag() {
        return authTag;
    }
}
