apply plugin: 'com.android.library'
apply plugin: 'com.kezong.fat-aar'
apply from: 'version.gradle'

def gitHash = "git rev-parse --short HEAD".execute().text.trim()
def isDirty = "git status --porcelain".execute().text.trim()
def buildTime = new Date().format("yyMMddHHmmss")
def buildId = isDirty ? "${gitHash}-dirty_${buildTime}" : "${gitHash}_${buildTime}"

android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 22
        versionCode appVersionCode
        versionName appVersionName
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
        setProperty("archivesBaseName", "Newland-NSDK-$versionName")

        buildConfigField "int", 'VERSION_CODE', String.valueOf(appVersionCode)
        buildConfigField 'String', 'VERSION_NAME', "\"" + appVersionName + "\""
        buildConfigField "String", "SDK_BUILD_ID", "\"${buildId}\""
    }

    buildTypes {
        debug {
            minifyEnabled false
        }

        release {
            minifyEnabled true
            zipAlignEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild.ndkBuild {
        path 'jni/Android.mk'
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }

    lintOptions {
        abortOnError false
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    testImplementation 'junit:junit:4.12'
//    implementation project(path: ':nsdkexternal')
//    embed project(path: ':nsdkexternal', configuration: 'default')
    embed project(path: ':nsdkcommon', configuration: 'default')
}

task generateSources(type: Jar) {
    classifier = 'sources'
    from ("../nsdkcommon/src/main/java"){
        include('com/newland/nsdk/core/api/common/**/*.java')
    }
    from ("src/main/java"){
        include('com/newland/nsdk/core/api/internal/**/*.java')
    }
    from ("../nsdkexternal/src/main/java"){
        include('com/newland/nsdk/core/api/external/**/*.java')
    }
    from ("../nsdkplugincard/src/main/java"){
        include('com/newland/nsdk/plugin/card/api/**/*.java')
    }
}

// build a jar with javadoc
task javadocJar(type: Jar) {
    classifier = 'javadoc'
    from 'doc'
}

def NEW_NAME = "Newland-NSDK-"+appVersionName

task unzipAar(dependsOn: ['assembleRelease'], type: Copy) {
    def zipFile = file("build/outputs/aar/"+NEW_NAME+"-release.aar")
    def outputDir = file("build/temp/aar")
    FileTree fileTree = zipTree(zipFile)
    from fileTree
    into outputDir
}

task addSourcesToClassesJar(dependsOn: ['unzipAar'], type: Jar) {
    archiveName "classes.jar"
    destinationDir file("build/temp")
    from zipTree("build/temp/aar/classes.jar")
    from ("../nsdkcommon/src/main/java"){
        include('com/newland/nsdk/core/api/**/*.java')
    }
    from ("src/main/java"){
        include('com/newland/nsdk/core/api/**/*.java')
    }
}

task addSourcesToAar(dependsOn: ['addSourcesToClassesJar'], type: Jar) {
    archiveName NEW_NAME+".aar"
    destinationDir file("build")
    from fileTree("build/temp/aar").exclude("classes.jar")
    from fileTree("build/temp").include("classes.jar")
}

tasks.whenTaskAdded { task ->
    if(task.name == "bundleReleaseAar" || task.name == "assembleRelease") {
        task.outputs.upToDateWhen { false }
    }
}

// 定义 JAR 文件的路径和解压缩目录
def jarFilePath = 'build/temp/classes.jar'
def extractDir = 'build/temp/jar'
// 创建一个任务解压 JAR 文件
task extractJar(dependsOn: ['addSourcesToClassesJar'], type: Copy) {
    from(zipTree(jarFilePath))
    into file(extractDir)
}
// 创建一个任务删除特定目录
task deleteDirectories(dependsOn: ['extractJar'], type: Delete) {
    // 定义需要删除的目录
    def directoriesToDelete = ["com/newland/me", "com/newland/nsdk/core/internal", "com/newland/nsdk/core/common", "android"]
    // 使用闭包延迟解析路径，要不然会文件夹并不会删除
    doLast {
        directoriesToDelete.each { folder ->
            def folderPath = extractDir + "/$folder"
            delete folderPath
        }
    }
}
// 创建一个任务重新打包 JAR 文件
task createJar(dependsOn: ['deleteDirectories'], type: Jar) {
    from file(extractDir)
    archiveFileName = NEW_NAME+".jar"
    destinationDirectory = file('build/temp')
}