/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_newland_ndk_NdkApiManager */
#include <android/log.h>

#define LOG_TAG "IntelligentLib"
#define LOGI(...) __android_log_print(ANDROID_LOG_VERBOSE,LOG_TAG,__VA_ARGS__)

#ifndef _Included_com_newland_ndk_NdkApiManager
#define _Included_com_newland_ndk_NdkApiManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_newland_ndk_NdkApiManager
 * Method:    NDK_Init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_newland_ndk_NdkApiManager_NDK_1Init
  (JNIEnv *env, jobject obj)
{
	LOGI("NDK_Init In NdkApiManager!");
	return NDK_Init();
}
#ifdef __cplusplus
}
#endif
#endif
